Repository mozilla-mobile/focus-android, pull requests merged in 2018-12, with the labels that each got.

#4004 Closes #4003 - Set Progress to Max in onPageFinished
  app/src/main/java/org/mozilla/focus/session/SessionCallbackProxy.kt
Labels: review

#3983 Fixes #3958 - Prevent URLbar from changing while crash reporter is visible
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: review

#3989 Fix IRC notification (broken build) and run master graphs on every br…
  .taskcluster.yml
Labels: review

#4007 String import 20181207-120849:
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pai/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
Labels: needs merge, review

#4011 Fixes #4010 - Restarts search suggestion job on enable
  app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsFetcher.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsViewModel.kt
Labels: review

#4008 RunBlocking Timeout not working
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
Labels: review

#4013 String import 20181212-121028
  app/src/main/res/values-ace/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-ur/strings.xml
Labels: needs merge, review

#3999 Closes #3995 - Make Accent color accessible against background color
  app/src/main/res/drawable/ic_trackers_blocked.xml
  app/src/main/res/values/colors.xml
Labels: review

#4001 Update compare-locales to recent major version, stop using l10n_base in config
  .taskcluster.yml
  l10n.toml
  tools/taskcluster/schedule-master-build.py
Labels: review

#4023 Fixes #4015 - Adds bo, sn and co to production locales
  app/src/main/java/org/mozilla/focus/widget/LocaleListPreference.java
  tools/l10n/android2po/env.py
  tools/l10n/locales.py
Labels: review

#4019 String import 20181213-120829
  app/src/main/res/values-te/strings.xml
  app/src/main/res/values-ur/strings.xml
Labels: needs merge, review

#4025 No Issue - bumps version
  app/build.gradle
Labels: review

#4024 No issue: Update GV 64 Rel Branch 12.13.18
  build.gradle
Labels: review

#4032 String import 20181214-121039
  app/src/main/res/values-jv/strings.xml
Labels: needs merge, review

#4033 No issue: Update GV Rel Branch 12.14.18
  build.gradle
Labels: review

#4038 No issue: Bump Version name to 8.0.4
  app/build.gradle
Labels: review

#4035 String import 20181215-121012
  app/src/main/res/values-jv/strings.xml
Labels: needs merge, review

#4029 Closes #3998: Make tips more visible
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/res/layout/fragment_urlinput.xml
Labels: review

#4031 Fixes #4030 - Adds settings to control ad blocking
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/privacy_security_settings.xml
Labels: review

#4039 Closes #2412 - Set locale with GV
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/WebFragment.kt
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
  app/src/main/java/org/mozilla/focus/web/IWebView.java
  app/src/main/java/org/mozilla/focus/webview/SystemWebView.kt
Labels: review

#4040 String import 20181218-120902
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-jv/strings.xml
  app/src/main/res/values-mix/strings.xml
Labels: needs merge, review

#4048 Fixes #4047: Hides adblock setting
  app/src/main/res/xml/privacy_security_settings.xml
Labels: review

#4049 Fixes #3617: Reverts "open with" default option
  app/src/main/java/org/mozilla/focus/activity/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
  app/src/main/java/org/mozilla/focus/utils/Browsers.java
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
  app/src/main/java/org/mozilla/focus/widget/DefaultBrowserPreference.java
Labels: review

#4042 Fixes #4036: Updates user list autocomplete string
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/autocomplete.xml
Labels: review

#4053 Do not trigger any Taskcluster job on tags
  .taskcluster.yml
Labels: review

#4061 String import 20181221-120908
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-jv/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
Labels: needs merge, review

#4066 String import 20181227-121811
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-jv/strings.xml
Labels: needs merge, review

#3972 Closes #3201 - Move Trash Can Erase Button to Toolbar
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.java
  app/src/androidTest/java/org/mozilla/focus/helpers/EspressoHelper.java
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/widget/FloatingEraseButton.java
  app/src/main/res/layout-sw600dp/toolbar.xml
  app/src/main/res/layout/fragment_browser.xml
  app/src/main/res/layout/toolbar.xml
Labels: feature, review

#4070 Handle malformed URLs without crashing
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: review

#4071 String import 20181228-121104
  app/src/main/res/values-pai/strings.xml
Labels: needs merge, review

#4043 Fixes #4041: Removes long label from erase&open
  app/src/focusBeta/res/xml-v25/shortcuts.xml
  app/src/focusDebug/res/xml-v25/shortcuts.xml
  app/src/focusNightly/res/xml-v25/shortcuts.xml
  app/src/focusRelease/res/xml-v25/shortcuts.xml
  app/src/klarDebug/res/xml-v25/shortcuts.xml
  app/src/klarNightly/res/xml-v25/shortcuts.xml
  app/src/klarRelease/res/xml-v25/shortcuts.xml
  app/src/main/res/values/strings.xml
Labels: review

#4076 refactor util classes to Kotlin
  app/src/main/java/org/mozilla/focus/utils/BitmapUtils.java
  app/src/main/java/org/mozilla/focus/utils/BitmapUtils.kt
  app/src/main/java/org/mozilla/focus/utils/HardwareUtils.java
  app/src/main/java/org/mozilla/focus/utils/HardwareUtils.kt
Labels: review
