Repository mozilla-mobile/focus-android, pull requests merged in 2018-09, with the labels that each got.

#3274 String import 20180901-000030
  app/src/main/res/values-ace/strings.xml
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-az/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cak/strings.xml
  app/src/main/res/values-cy/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-dsb/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en-rCA/strings.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rCL/strings.xml
  app/src/main/res/values-es-rMX/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-fy-rNL/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-hus/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-kk/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mix/strings.xml
  app/src/main/res/values-mr/strings.xml
  app/src/main/res/values-ms/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-oc/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ppl/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-su/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-th/strings.xml
  app/src/main/res/values-trs/strings.xml
  app/src/main/res/values-tsz/strings.xml
  app/src/main/res/values-tt/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: needs merge, review

#3275 String import 20180901-121001
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-lo/strings.xml
  app/src/main/res/values-mr/strings.xml
  app/src/main/res/values-sr/strings.xml
Labels: needs merge, review

#3268 No Issue: Update AC Version to 0.21
  build.gradle
Labels: review

#3278 No Issue - Modifies build task for master
  tools/taskcluster/schedule-master-build.py
Labels: review

#3283 No Issue - Removes accept license step from release build task
  tools/taskcluster/release.py
Labels: review

#3288 String import 20180903-121119
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-kab/strings.xml
  app/src/main/res/values-nn-rNO/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
Labels: needs merge, review

#3301 String import 20180904-120638
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-te/strings.xml
Labels: needs merge, review

#3279 Update GV Rel Branch 2018.08.31
  build.gradle
Labels: review

#3307 Fixes #3304: Home screen tips toggle improperly indented
  app/src/main/res/xml/mozilla_settings.xml
Labels: needs merge

#3272 Closes #2879 Open Rights and About From Settings in InfoActivity WebView
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/focus/activity/InfoActivity.kt
  app/src/main/java/org/mozilla/focus/browser/LocalizedContent.java
  app/src/main/java/org/mozilla/focus/fragment/InfoFragment.kt
  app/src/main/java/org/mozilla/focus/settings/MozillaSettingsFragment.kt
  app/src/main/res/layout/activity_info.xml
  app/src/main/res/layout/fragment_info.xml
  app/src/main/res/xml/mozilla_settings.xml
  app/src/test/java/org/mozilla/focus/utils/InfoActivityIntentTest.kt
Labels: review

#3299 Issue #3190: Convert Java classes to Kotlin to make browser-session integration easier.
  app/src/main/java/org/mozilla/focus/browser/LocalizedContent.java
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/menu/browser/RequestDesktopCheckItemViewHolder.java
  app/src/main/java/org/mozilla/focus/menu/browser/RequestDesktopCheckItemViewHolder.kt
  app/src/main/java/org/mozilla/focus/menu/context/WebContextMenu.java
  app/src/main/java/org/mozilla/focus/menu/context/WebContextMenu.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
  app/src/main/java/org/mozilla/focus/session/NotificationSessionObserver.java
  app/src/main/java/org/mozilla/focus/session/NotificationSessionObserver.kt
  app/src/main/java/org/mozilla/focus/session/SessionNotificationService.java
  app/src/main/java/org/mozilla/focus/session/SessionNotificationService.kt
  app/src/main/java/org/mozilla/focus/session/ui/SessionsAdapter.java
  app/src/main/java/org/mozilla/focus/session/ui/SessionsAdapter.kt
  app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.java
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
  app/src/main/java/org/mozilla/focus/web/ClassicWebViewProvider.java
  app/src/main/java/org/mozilla/focus/webview/SystemWebView.java
  app/src/main/java/org/mozilla/focus/webview/SystemWebView.kt
  app/src/main/java/org/mozilla/focus/widget/DefaultBrowserPreference.java
  app/src/test/java/org/mozilla/focus/utils/SupportUtilsTest.java
  app/src/test/java/org/mozilla/focus/utils/SupportUtilsTest.kt
Labels: review

#3318 String import 20180905-120905
  app/src/main/res/values-ace/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-oc/strings.xml
  app/src/main/res/values-ppl/strings.xml
  app/src/main/res/values-tr/strings.xml
Labels: needs merge, review

#3223 add tip screenshot for 7.0
  Screengrabfile
  app/src/androidTest/java/org/mozilla/focus/screenshots/BrowserScreenScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/FirstRunScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/HomeScreenScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/SettingsScreenshots.java
Labels: review

#3311 Closes #3290 & Closes #3291: Modifying search engine crashes
  app/src/main/java/org/mozilla/focus/search/RadioSearchEngineListPreference.kt
Labels: review

#3323 Remove visited URL from logs Closes #3313
  app/src/main/java/org/mozilla/focus/observer/LoadTimeObserver.kt
Labels: review

#3321 Clear confusion with "focus:test" GV toggle
  app/src/debug/java/org/mozilla/focus/web/Config.kt
  app/src/focusRelease/java/org/mozilla/focus/web/Config.kt
  app/src/klarRelease/java/org/mozilla/focus/web/Config.kt
  app/src/main/java/org/mozilla/focus/settings/ExperimentsSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/utils/Experiments.kt
  app/src/nightly/java/org/mozilla/focus/web/Config.kt
Labels: review

#3330 Fix detekt check in TaskCluster
  app/src/main/java/org/mozilla/focus/settings/SettingsFragment.kt
Labels: review

#3329 #3236 Disable GV Safe Browsing
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
Labels: review

#3331 Fixes #3306: Correct boolean expresion in AppConstants.isGeckoBuild's get()
  app/src/main/java/org/mozilla/focus/utils/AppConstants.kt
Labels: P1

#3332 Record experiment names instead of IDs
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/utils/Experiments.kt
Labels: review

#3333 No issue: Suspend Media When Inactive GV
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
Labels: review

#3336 Fix AccessAboutAndYourRightsPagesTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/AccessAboutAndYourRightsPagesTest.java
Labels: needs merge, review

#3334 Fixes #3297: No return path after tapping on ℹ️
  app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt
Labels: review

#3339 Fixes #3155: Update UI tests to reflect search suggestion changes.
  app/src/androidTest/java/org/mozilla/focus/activity/ChangeSearchEngineTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsBlockToggleTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchLocaleTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/URLMismatchTest.java
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.java
Labels: review

#3345 No issue: Update GV 2018.09.07
  build.gradle
Labels: review

#3337 No issue: Use WebView in InfoActivity only for focus:rights
  app/src/main/java/org/mozilla/focus/activity/InfoActivity.kt
Labels: review

#3348 Closes #3217 Disable Crash Reporting Before Release
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
Labels: review

#3351 No issue: Update Constraint Layout and AC Version
  app/build.gradle
  build.gradle
Labels: review

#3350 No issue: Update to Support Library 28.0.0-rc02
  build.gradle
Labels: review

#3355 No Issue - Bumps version number
  app/build.gradle
Labels: review

#3357 Urlactestfix
  app/src/androidTest/java/org/mozilla/focus/activity/URLAutocompleteTest.java
Labels: review

#3352 ScreenshotTest is no longer dependent on search suggestion dialog acceptance
  app/src/androidTest/java/org/mozilla/focus/screenshots/BrowserScreenScreenshots.java
Labels: review

#3354 Disable webview test that permanently fails
  app/src/androidTest/java/org/mozilla/focus/privacy/WebViewDataTest.java
Labels: review

#3356 No Issue - Bumps version number
  app/build.gradle
Labels: review

#3359 Hide appbar and FAB in Fullscreen Mode with GV Closes #3353
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: review

#3360 No issue: Add extension function for Context typecasting
  app/src/main/java/org/mozilla/focus/settings/LearnMoreSwitchPreference.kt
  app/src/main/java/org/mozilla/focus/utils/ContextUtils.kt
Labels: P1

#3368 Address Firebase UI Test failures
  app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/ImageSelectTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsBlockToggleTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchLocaleTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/ToggleBlockTest.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/BrowserScreenScreenshots.java
Labels: review

#3285 Fixes #2930: After FirstrunFragment create new UrlInputFragment
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/FirstrunFragment.java
Labels: P1

#3341 Fixes #3287: Dismiss and recreate HomeMenu when an orientation change occurs
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/menu/home/HomeMenu.kt
Labels: P1

#3346 Closes #2964: Just-in time information - Tracking Protection
  app/src/main/res/layout/menu.xml
  app/src/main/res/layout/menu_blocking_switch.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: review

#3358 No issue: Fix displayed URL for internal pages in GV
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
Labels: review

#3361 Fixes #2989: Remove show badge notification channel
  app/src/main/java/org/mozilla/focus/session/SessionNotificationService.kt
Labels: P1

#3369 No issue: Fixes Scrolling in WebView while selecting text
  app/src/main/res/layout/fragment_browser.xml
Labels: review

#3377 Fixes #3376: jacoco doesn't generate java code coverage
  app/build.gradle
Labels: review

#3383 For #3372 - Adds completed locales
  tools/l10n/locales.py
Labels: review

#3382 Fixes #3365: Fix contrast ratio of caption/hint labels on Settings
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: review

#3381 Fixes #3366: Fix contrast ratio of search placeholder text
  app/src/main/res/values/colors.xml
Labels: review

#3380 Fixes #3379: Unnecessary jacoco-android dependency
  build.gradle
Labels: review

#3384 No issue: Update 62 Rel Branch 09.11.18
  build.gradle
Labels: review

#3385 Closes #3364 GV Prompt Style Crash
  app/src/main/java/org/mozilla/focus/gecko/GeckoViewPrompt.java
  app/src/main/res/values/styles.xml
Labels: review

#3388 Taskcluster: Use json-e to generate tasks
  .taskcluster.yml
Labels: P1

#3389 Taskcluster: Fix json-e events
  .taskcluster.yml
Labels: P1

#3390 Closes #3370 Do not Init Sentry for Unsupported Versions
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
Labels: review

#3271 Consider going directly to website when clicking on a URL in suggestions
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/menu/browser/BrowserMenu.java
  app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsViewModel.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
  app/src/main/java/org/mozilla/focus/utils/ViewUtils.java
  app/src/main/java/org/mozilla/focus/utils/ViewUtils.kt
  app/src/main/res/layout/item_suggestion.xml
  app/src/main/res/values/dimens.xml
  app/src/test/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsViewModelTest.kt
Labels: P1, review

#3393 Handle open tab on background behavior on UI Tests
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/BrowserScreenScreenshots.java
Labels: review

#3397 Taskcluster: Fix missing environment variables
  .taskcluster.yml
Labels: P1

#3405 fix: remove geckoview UI tests on Firebase
  tools/taskcluster/schedule-master-build.py
Labels: review

#3406 String import 20180913-200848
  app/src/main/res/values-ace/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ast/strings.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-hus/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-jv/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nn-rNO/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-sq/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-trs/strings.xml
Labels: needs merge, review

#3407 No Issue - Bump version
  app/build.gradle
Labels: review

#3412 String import 20180914-121127
  app/src/main/res/values-ia/strings.xml
Labels: needs merge, review

#3403 Fixes #2943: Missing "button" text on more options home screen
  app/src/main/res/layout/fragment_urlinput.xml
  app/src/main/res/values/strings.xml
Labels: review

#3415 Closes #3394 Remove Transparent Background from Dialogs with WindowBa…
  app/src/main/java/org/mozilla/focus/fragment/AddToHomescreenDialogFragment.java
  app/src/main/java/org/mozilla/focus/gecko/GeckoViewPrompt.java
Labels: review

#3413 No issue - Block on reading Fretboard experiments from disk
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
Labels: review

#3414 Closes #3401 Disable Search Terms or URL Feature For DDG Users on GV
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: review

#3423 Taskcluster: Fix release variables
  .taskcluster.yml
Labels: P1

#3421 String import 20180915-120958
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-my/strings.xml
Labels: needs merge, review

#3420 No issue: Update GV Rel Branch 09.14.2018
  build.gradle
Labels: review

#3427 No Issue - Version bump
  app/build.gradle
Labels: review

#3425 Add explicit Java 8 support
  app/build.gradle
Labels: review

#3428 Closes #3373: Make string for switch to new tab shorter
  app/src/main/res/values/strings.xml
Labels: review

#3419 No issue: bump Kotlin + Android Components versions
  build.gradle
Labels: review

#3436 String import 20180918-120945
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-my/strings.xml
  app/src/main/res/values-ur/strings.xml
Labels: needs merge, review

#3435 Fixes #3434, Telemetry records empty A/B experiments list
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
Labels: review

#3429 Fixes #2944, "Search for" hint should be read after clear button
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
Labels: review

#3442 String import 20180919-121351
  app/src/main/res/values-iw/strings.xml
Labels: needs merge, review

#3432 Sentry Crash FOCUS-ANDROID-4A add clearView safe call
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: review

#3433 No issue: Replace context!! and activity!! with safer require methods
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: review

#3446 Closes #3444 Allow App Link Data to be null in WebContextMenu
  app/src/main/java/org/mozilla/focus/menu/context/WebContextMenu.kt
Labels: review

#3445 Fixes #3362 - Changes string for search engine setting
  app/src/androidTest/java/org/mozilla/focus/screenshots/BrowserScreenScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/SettingsScreenshots.java
  app/src/main/java/org/mozilla/focus/search/SearchEnginePreference.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/search_settings.xml
Labels: review

#3450 Use best effort to load experiments on initial startup
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
Labels: review

#3453 Fixes #3451 - Updates active whats new background
  app/src/main/res/drawable/menu_item_dark_background.xml
Labels: review, 🚀 needs uplift

#3454 No issue: remove sputnik from readme.
  README.md
Labels: review

#3458 String import 20180921-120906
  app/src/main/res/values-ixl/strings.xml
Labels: needs merge, review

#3437 Closes 2896: Just in time default browser
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/activity/SettingsActivity.kt
  app/src/main/java/org/mozilla/focus/locale/LocaleAwareAppCompatActivity.java
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
  app/src/main/java/org/mozilla/focus/utils/Browsers.java
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
  app/src/main/java/org/mozilla/focus/widget/DefaultBrowserPreference.java
Labels: review

#3456 Closes #3124 Reload Page when Relevant Preferences Are Changed
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
  app/src/main/java/org/mozilla/focus/webview/SystemWebView.kt
Labels: review

#3459 No issue: Update GV 09.21
  build.gradle
Labels: review

#3464 String import 20180922-120755
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-trs/strings.xml
Labels: needs merge, review

#3468 String import 20180924-120820
  app/src/main/res/values-bo/strings.xml
  app/src/main/res/values-lt/strings.xml
Labels: needs merge, review

#3469 Issue #3443: Figure out Why GV A/B Experiment Isn't Rolling Out
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetrySettingsProvider.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/utils/Experiments.kt
  app/src/main/java/org/mozilla/focus/utils/ExperimentsSyncService.kt
  app/src/main/res/values/preference_keys.xml
  build.gradle
Labels: review

#3475 For #3474 - Ensures fretboard pref gets sent with telemetry
  app/src/main/java/org/mozilla/focus/telemetry/TelemetrySettingsProvider.kt
Labels: review

#3476 String import 20180925-121523
  app/src/main/res/values-am/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-ta/strings.xml
Labels: needs merge, review

#3471 Fix type error in locale lookup
  app/src/main/java/org/mozilla/focus/widget/LocaleListPreference.java
Labels: P1

#3447 No issue: Removed redundant variable in UrlInputFragment
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: P1

#3481 For #3443 - Uses new version of FlatFileStorage
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/fretboard/FocusFlatFileStorage.kt
Labels: review

#3431 Make GV tests use GV for Klar, WV for Focus
  app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/AddToHomescreenTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/EraseAllUserDataTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/FirstRunDialogueTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/OpenInExternalBrowserDialogueTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsBlockToggleTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchLocaleTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/ToggleBlockTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/URLAutocompleteTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/URLMismatchTest.java
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.java
Labels: review

#3483 String import 20180926-121015
  app/src/main/res/values-ace/strings.xml
  app/src/main/res/values-pl/strings.xml
Labels: needs merge, review

#3491 No issue: Update GV 62 Rel Branch
  build.gradle
Labels: review

#3494 String import 20180927-120827
  app/src/main/res/values-ixl/strings.xml
  app/src/main/res/values-yua/strings.xml
Labels: needs merge, review

#3503 String import 20180928-121733
  app/src/main/res/values-eo/strings.xml
Labels: needs merge, review

#3502 Fixes #3495 - Sets Selectable Item Background for Search Suggestions
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
  app/src/main/res/layout/fragment_search_suggestions.xml
Labels: review

#3499 For #3404 - Updates Disable tips tip string
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
  app/src/main/res/values/strings.xml
Labels: review

#3497 For #3467 - Replaces autocomplete strings
  app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteDefaultDomainsPreference.kt
  app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteListFragment.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/autocomplete.xml
Labels: review

#3516 For #3487 - Fixes the A/B test logic for homescreen tips
  app/src/main/java/org/mozilla/focus/settings/MozillaSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/xml/mozilla_settings.xml
Labels: review

#3518 No issue: Update GV 09.28
  build.gradle
Labels: review
