Repository mozilla-mobile/focus-android, pull requests merged in 2018-07, with the labels that each got.

#2833 String import 20180630-120726
  app/src/main/res/values-cak/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-gu-rIN/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-ixl/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ta/strings.xml
  app/src/main/res/values-trs/strings.xml
  app/src/main/res/values-tsz/strings.xml
Labels: needs merge

#2834 String import 20180702-121047
  app/src/main/res/values-bs/strings.xml
  app/src/main/res/values-ixl/strings.xml
Labels: needs merge

#2839 Enable Remote Debugging Through Advanced Setting Closes #2647
  app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java
  app/src/main/java/org/mozilla/focus/settings/AdvancedSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/settings/SettingsFragment.java
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/advanced_settings.xml
  app/src/main/res/xml/settings.xml
Labels: needs merge

#2853 Fixes #2846 - Correct the ordering of when statement so custom items …
  app/src/main/java/org/mozilla/focus/menu/browser/BrowserMenuAdapter.kt
Labels: needs review

#2856 String import 20180706-120433
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-ixl/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-te/strings.xml
  app/src/main/res/values-tsz/strings.xml
  app/src/main/res/values-tt/strings.xml
  app/src/main/res/values-ur/strings.xml
  app/src/main/res/values-vi/strings.xml
Labels: needs merge

#2862 String import 20180707-120853
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-ur/strings.xml
Labels: needs merge

#2865 String import 20180709-121926
  app/src/main/res/values-gu-rIN/strings.xml
Labels: needs merge

#2874 For #2871 - Adds a proper name for the Tsz locale
  app/src/main/java/org/mozilla/focus/widget/LocaleListPreference.java
Labels: needs merge

#2878 Update GeckoView to 62.0b7 Closes #2875
  build.gradle
Labels: needs review

#2880 Update order of GV onCrash
  app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java
Labels: needs review

#2697 Updated Delete FAB icon (#2682)
  app/src/main/res/drawable/ic_delete.xml
Labels: blocked

#2895 Fix test failures in AddtoHSTest.java - Closes #2873
  app/src/androidTest/java/org/mozilla/focus/activity/AddtoHSTest.java
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.java
Labels: automation, testing

#2762 Show page title instead of URL for tabs sheet Closes #1365
  app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java
  app/src/main/java/org/mozilla/focus/session/Session.java
  app/src/main/java/org/mozilla/focus/session/SessionCallbackProxy.java
  app/src/main/java/org/mozilla/focus/session/ui/SessionViewHolder.kt
  app/src/main/java/org/mozilla/focus/web/IWebView.java
  app/src/webview/java/org/mozilla/focus/webview/SystemWebView.java
Labels: needs merge

#2881 String import 20180711-120743
  app/src/main/res/values-ay/strings.xml
  app/src/main/res/values-kw/strings.xml
Labels: needs merge

#2918 String import 20180717-121209
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-bn-rBD/strings.xml
  app/src/main/res/values-quc/strings.xml
  app/src/main/res/values-th/strings.xml
Labels: needs merge

#2917 Initialize sentry from application.
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/activity/MainActivity.java
Labels: needs review

#2907 GV Turn off TP + Cookie Blocking with Menu Toggle Closes #2894
  app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java
Labels: needs merge

#2923 Refactor UI tests with standard test names and TestRail links - Closes #2922
  app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/AddToHomescreenTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/EraseAllUserDataTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/FirstRunDialogueTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/OpenInExternalBrowserDialogueTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/PullDownToRefreshTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchLocaleTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/URLAutocompleteTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/AccessAboutAndYourRightsPagesTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/ChangeSearchEngineTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/CustomTabTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/DownloadFileTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/ShareWebsiteTest.java
Labels: automation, testing

#2929 Set GeckoSession active and inactive in onResume and onPause
  app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java
Labels: needs review

#2906 Send Histogram Data for Load Times Closes #2891
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java
  app/src/main/java/org/mozilla/focus/observer/AverageLoadTimeObserver.java
  app/src/main/java/org/mozilla/focus/observer/LoadTimeObserver.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: needs merge

#2972 Fixes #2970 - Updates Android Components
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  build.gradle
Labels: needs review

#2977 Set default value for Renderer preference in settings fragment based …
  app/src/main/java/org/mozilla/focus/settings/ExperimentsSettingsFragment.kt
  app/src/main/res/xml/experiments_settings.xml
Labels: needs review

#2978 String import 20180725-121300
  app/src/main/res/values-ast/strings.xml
  app/src/main/res/values-gu-rIN/strings.xml
  app/src/main/res/values-th/strings.xml
Labels: needs merge

#2983 Rename renderer preference to fix Nightly users stuck on the Webview
  app/src/main/java/org/mozilla/focus/settings/ExperimentsSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/web/WebViewProvider.kt
  app/src/main/res/xml/experiments_settings.xml
Labels: needs review

#2993 String import 20180726-120610
  app/src/main/res/values-pa-rIN/strings.xml
  app/src/main/res/values-pai/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-quc/strings.xml
Labels: needs merge

#3002 String import 20180727-120625
  app/src/main/res/values-pa-rIN/strings.xml
  app/src/main/res/values-ur/strings.xml
Labels: needs merge

#3003 Apply IME flag NoPersonalizedLearning to find in page input.
  app/src/main/res/layout/find_in_page.xml
Labels: needs review

#2872 Fix slow opening of settings screen
  app/src/main/java/org/mozilla/focus/widget/LocaleListPreference.java
Labels: needs review

#3008 Update screengrabfile to use new build flavors
  Screengrabfile
Labels: needs review

#3023 Closes #3022 Only Send Native Crash Reporting if Telemetry Enabled
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
Labels: needs review

#3028 String import 20180731-121153
  app/src/main/res/values-eo/strings.xml
Labels: needs merge

#3020 Closes #2852 - on back pressed check if full screen and close
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java
Labels: needs review
