Repository mozilla-mobile/focus-android, pull requests merged in 2018-06, with the labels that each got.

#2665 Allow copying URL in Custom Tabs Closes #2297
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java
  app/src/main/res/values/strings.xml
Labels: needs merge

#2693 GV Update 6.1.2018
  build.gradle
Labels: needs review

#2694 Update GV 06.04.2018
  build.gradle
Labels: needs merge

#2698 Update GV 06.05.2018
  build.gradle
Labels: needs review

#2704 Update GV 06.06.2018
  build.gradle
Labels: needs review

#2715 Update GV 06.07.18
  build.gradle
Labels: needs review

#2707 Closes #2654 - Adds Pai pai to the screenshot locale list
  tools/l10n/android2po/env.py
  tools/l10n/locales.py
Labels: needs merge

#2716 String import 20180607-210335
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-az/strings.xml
  app/src/main/res/values-bs/strings.xml
  app/src/main/res/values-cak/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-cy/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-dsb/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en-rCA/strings.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-es-rCL/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es-rMX/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-fy-rNL/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ixl/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-kab/strings.xml
  app/src/main/res/values-kk/strings.xml
  app/src/main/res/values-kw/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mix/strings.xml
  app/src/main/res/values-ms/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-nn-rNO/strings.xml
  app/src/main/res/values-oc/strings.xml
  app/src/main/res/values-pai/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-quy/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-ta/strings.xml
  app/src/main/res/values-th/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-tsz/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zam/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: needs merge

#2722 String import 20180608-120648
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-fy-rNL/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-kab/strings.xml
  app/src/main/res/values-ms/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-nn-rNO/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
Labels: needs merge

#2723 Update GV 06.08.2018
  build.gradle
Labels: needs merge

#2736 Update GV 06.13.2018 and fix IllegalStateCrash for geckoSession still…
  app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java
  build.gradle
Labels: needs review

#2695 Hide data: Urls and show focus:<keyword> Closes #2506
  app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java
Labels: needs merge

#2744 Update GV 06.15.18
  build.gradle
Labels: needs review

#2742 Add Install Packages Permission to install downloaded APKs on O+ Closes #1063
  app/src/main/AndroidManifest.xml
Labels: needs review

#2749 String import 20180615-233217 🔄
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ay/strings.xml
  app/src/main/res/values-az/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cak/strings.xml
  app/src/main/res/values-cy/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-dsb/strings.xml
  app/src/main/res/values-en-rCA/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rCL/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ixl/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-kk/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-oc/strings.xml
  app/src/main/res/values-pa-rIN/strings.xml
  app/src/main/res/values-pai/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-te/strings.xml
  app/src/main/res/values-th/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-trs/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: needs merge

#2751 String import 20180618-120859
  app/src/main/res/values-lt/strings.xml
Labels: needs merge

#2782 Hide First Run tabs from screen reader Closes #2781
  app/src/main/res/layout/fragment_firstrun.xml
Labels: needs review

#2778 Move scrolling appbar view behavior to IWebView Closes #2776 Closes #…
  app/src/main/res/layout/fragment_browser.xml
Labels: needs review

#2800 String import 20180626-120631
  app/src/main/res/values-tsz/strings.xml
Labels: needs merge

#2798 Fix assert failure in SearchEngineSelectionTest.java - Closes #2793 ⚡️
  app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java
Labels: testing

#2761 Add Sentry capture to GeckoView onCrash Closes #2731
  app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java
  app/src/main/java/org/mozilla/focus/telemetry/SentryWrapper.kt
Labels: needs review

#2815 Remove custom tab session when closing custom tab Closes #2812
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java
Labels: needs review

#2825 Enable remote debugging for GV Closes #2647
  app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java
Labels: needs merge

#2810 String import 20180627-121143
  app/src/main/res/values-anp/strings.xml
Labels: needs merge
