Repository mozilla-mobile/focus-android, pull requests merged in 2018-05, with the labels that each got.

#2570 String import 20180501-120701
  app/src/main/res/values-kw/strings.xml
Labels: needs merge

#2562 Fix for #2554
  app/build.gradle
Labels: needs merge

#2578 String import 20180502-120921
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-bn-rBD/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-kw/strings.xml
Labels: needs merge

#2574 Add “Privacy” and “Performance” menu in Settings Closes #2357
  app/src/main/java/org/mozilla/focus/settings/PrivacySecuritySettingsFragment.kt
  app/src/main/java/org/mozilla/focus/settings/SettingsFragment.java
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/privacy_security_settings.xml
  app/src/main/res/xml/settings.xml
Labels: needs merge

#2558 Bug 1409091 - Add mandatory but unused ChainOfTrust artifacts
  .taskcluster.yml
  tools/taskcluster/release.py
Labels: needs merge

#2545 Gecko Nightlies
  .taskcluster.yml
  tools/taskcluster/lib/tasks.py
  tools/taskcluster/release.py
Labels: blocked

#2572 Use e10s for GV Closes #2445
  app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java
  build.gradle
Labels: needs merge

#2582 Closes #2581: Upgrade to android-components 0.5.1
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  build.gradle
Labels: needs review

#2588 String import 20180505-120617
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-gu-rIN/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-iw/strings.xml
  app/src/main/res/values-tt/strings.xml
Labels: needs merge

#2589 String import 20180506-120826
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-oc/strings.xml
Labels: needs merge

#2601 updates version number
  app/build.gradle
Labels: needs merge

#2598 Update Gecko to 62
  build.gradle
Labels: needs merge

#2609 Show "Report Site Issue" for GeckoView builds only 🔃
  app/src/main/java/org/mozilla/focus/menu/browser/BrowserMenuAdapter.java
Labels: needs merge

#2613 Remove unused description ✂️
  app/src/main/res/values/strings.xml
Labels: needs merge

#2618 Remove "feedback" from Mozilla description 🐰 Closes #2617
  app/src/main/res/values/strings.xml
Labels: needs merge

#2611 Update GeckoView 2018.05.14
  build.gradle
Labels: needs review

#2622 Enable Search Terms or URL for GeckoView Closes #2103
  app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java
  app/src/main/java/org/mozilla/focus/utils/Features.kt
Labels: needs review

#2621 Update Gecko 5.15.18
  build.gradle
Labels: needs review

#2623 Better string descriptions for l10n
  app/src/main/res/values/strings.xml
Labels: needs review

#2641 Update GV 5.22.18
  build.gradle
Labels: needs review

#2652 String import 20180523-161844
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ast/strings.xml
  app/src/main/res/values-az/strings.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-bs/strings.xml
  app/src/main/res/values-cy/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-dsb/strings.xml
  app/src/main/res/values-en-rCA/strings.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rCL/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es-rMX/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-fy-rNL/strings.xml
  app/src/main/res/values-ga-rIE/strings.xml
  app/src/main/res/values-gu-rIN/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-kab/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-kw/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-meh/strings.xml
  app/src/main/res/values-mix/strings.xml
  app/src/main/res/values-ms/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-ne-rNP/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-oc/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sq/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-ta/strings.xml
  app/src/main/res/values-th/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zam/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: needs merge

#2658 String import 20180524-121222
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-cy/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-dsb/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rCL/strings.xml
  app/src/main/res/values-fy-rNL/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-kab/strings.xml
  app/src/main/res/values-ms/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-ne-rNP/strings.xml
  app/src/main/res/values-nn-rNO/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
Labels: needs merge

#2661 String import 20180525-121404
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-bs/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-oc/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-sq/strings.xml
  app/src/main/res/values-th/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: needs merge

#2653 Add disabling Cookies + 3rd party Cookies for GeckoView Closes #2448
  app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java
  build.gradle
Labels: needs merge

#2674 Show Security Info on Tablets Closes #2671
  app/src/main/res/layout-sw600dp/toolbar.xml
Labels: needs merge

#2643 Handle First Run A11y Detach UrlInputFragment Closes #2615
  app/src/main/java/org/mozilla/focus/fragment/FirstrunFragment.java
Labels: needs merge

#2675 Update GV 5.29.18 🦎
  build.gradle
Labels: needs merge
