Repository mozilla-mobile/focus-android, pull requests merged in 2018-04, with the labels that each got.

#2406 1647: Order browser list alphabetically
  app/src/main/java/org/mozilla/focus/search/SearchEngineListPreference.java
Labels: needs review

#2411 String import 20180330-120543
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
Labels: needs merge

#2424 String import 20180404-120749
  app/src/main/res/values-gu-rIN/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-nn-rNO/strings.xml
Labels: needs merge

#2160 Separate Focus Webview UI Tests from Gecko ones
  app/build.gradle
  app/src/androidTest/java/org/mozilla/focus/activity/AdBlockingTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/AddtoHSTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/OnBoardingTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/OpenwithDialogTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/PageVisitTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/PullDownToRefreshTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsAppearanceTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchLocaleTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/ToggleBlockTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/TrashcanTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/TypicalUseScenarioTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/URLCompletionTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/URLMismatchTest.java
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/BadURLTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/CustomTabTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/DownloadTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/ImageSelectTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/MultitaskingTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/RestartTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/SearchEngineSelectionTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/ShareDialogTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/SwitchContextTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/helpers/WebViewFakeLongPress.java
  app/src/androidTestWebview/java/org/mozilla/focus/privacy/LocalSessionStorageTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/privacy/WebViewDataTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/screenshots/BrowserScreenScreenshots.java
  app/src/androidTestWebview/java/org/mozilla/focus/screenshots/ErrorPagesScreenshots.java
  app/src/androidTestWebview/java/org/mozilla/focus/screenshots/FirstRunScreenshots.java
  app/src/androidTestWebview/java/org/mozilla/focus/screenshots/HomeScreenScreenshots.java
  app/src/androidTestWebview/java/org/mozilla/focus/screenshots/NotificationScreenshots.java
  app/src/androidTestWebview/java/org/mozilla/focus/screenshots/ScreenshotTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/screenshots/SettingsScreenshots.java
Labels: needs review

#2291 Followup to #2160: Modify Taskcluster script to run Geckoview/Webview UI tests
  tools/taskcluster/execute-firebase-test.sh
  tools/taskcluster/schedule-master-build.py
Labels: needs review

#2428 String import 20180405-120632
  app/src/main/res/values-gu-rIN/strings.xml
Labels: needs merge

#2438 Update versionName for 4.2
  app/build.gradle
Labels: needs review

#2437 String import 20180408-120931
  app/src/main/res/values-anp/strings.xml
Labels: needs merge

#2432 Don't require %s at end of string for adding search engine Closes #1960
  app/src/main/java/org/mozilla/focus/utils/UrlUtils.java
Labels: needs merge

#2431 Fix "Trackers blocked" string truncated in multiple locales Closes #2341 🌶
  app/src/main/res/layout/menu_blocking_switch.xml
Labels: needs merge

#2442 Fixes #2435: Refactor domain auto-completion to re-use new components
  app/build.gradle
  app/src/androidTestWebview/java/org/mozilla/focus/screenshots/SettingsScreenshots.java
  app/src/main/assets/domains/br
  app/src/main/assets/domains/ca
  app/src/main/assets/domains/de
  app/src/main/assets/domains/fr
  app/src/main/assets/domains/gb
  app/src/main/assets/domains/global
  app/src/main/assets/domains/hk
  app/src/main/assets/domains/id
  app/src/main/assets/domains/in
  app/src/main/assets/domains/pl
  app/src/main/assets/domains/ru
  app/src/main/assets/domains/sg
  app/src/main/assets/domains/tw
  app/src/main/assets/domains/us
  app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteAddFragment.kt
  app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteListFragment.kt
  app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteRemoveFragment.kt
  app/src/main/java/org/mozilla/focus/autocomplete/CustomAutocomplete.kt
  app/src/main/java/org/mozilla/focus/autocomplete/UrlAutoCompleteFilter.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/widget/InlineAutocompleteEditText.java
  app/src/main/res/layout/fragment_urlinput.xml
  app/src/test/java/org/mozilla/focus/autocomplete/CustomAutocompleteTest.kt
  app/src/test/java/org/mozilla/focus/autocomplete/UrlAutoCompleteFilterTest.kt
  build.gradle
Labels: needs review

#2451 Update versionName for 5.0
  app/build.gradle
Labels: needs review

#2453 String import 20180412-120815
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-bs/strings.xml
  app/src/main/res/values-cy/strings.xml
  app/src/main/res/values-dsb/strings.xml
  app/src/main/res/values-es-rCL/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-fy-rNL/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-ms/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-th/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: needs merge

#2434 Closes #2426 - Update Telemetry search engine to return 'custom'.
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: needs merge

#2430 Support Cookie 🍪 blocking Closes #2330
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings.xml
  app/src/webview/java/org/mozilla/focus/web/WebViewProvider.java
  app/src/webview/java/org/mozilla/focus/webview/SystemWebView.java
Labels: needs review

#2358 Use NotificationCompat in Builder
  app/src/main/java/org/mozilla/focus/session/SessionNotificationService.java
Labels: needs merge

#2457 String import 20180413-120624 🔃
  app/src/main/res/values-bs/strings.xml
  app/src/main/res/values-cy/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-dsb/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rCL/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-kk/strings.xml
  app/src/main/res/values-ms/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-nn-rNO/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-th/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: needs merge

#2466 WebView should show focus:rights and focus:about URL Closes #2455
  app/src/main/java/org/mozilla/focus/browser/LocalizedContent.java
Labels: needs review

#2474 String import 20180418-121358
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-bs/strings.xml
  app/src/main/res/values-cy/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-dsb/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ms/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-tt/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: needs merge

#2477 New What's New Link for 4.2
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.java
Labels: needs review

#2443 Add crash reporting via Sentry 🎈
  .gitignore
  .taskcluster.yml
  app/build.gradle
  app/lint.xml
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/focus/activity/MainActivity.java
  app/src/main/java/org/mozilla/focus/telemetry/SentryWrapper.kt
  tools/taskcluster/get-sentry-token.py
Labels: needs review

#2481 String import 20180419-121255
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rMX/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-kab/strings.xml
  app/src/main/res/values-kk/strings.xml
  app/src/main/res/values-nn-rNO/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-th/strings.xml
Labels: needs merge

#2490 String import 20180420-120621
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn-rBD/strings.xml
  app/src/main/res/values-es-rCL/strings.xml
  app/src/main/res/values-fy-rNL/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-oc/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
Labels: needs merge

#2485 Remove Unused InfoFragment+InfoActivity and layouts Closes #2484  🔃
  app/src/main/java/org/mozilla/focus/fragment/InfoFragment.java
  app/src/main/res/layout/activity_info.xml
  app/src/main/res/layout/fragment_info.xml
Labels: needs review

#2483 Callback null checks in GV WebViewProvider 🙏🏻 Closes #2482
  app/src/gecko/java/org/mozilla/focus/web/WebViewProvider.java
Labels: needs review

#2458 fix UI Test failures
  app/src/androidTest/java/org/mozilla/focus/activity/PageVisitTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/URLMismatchTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/BadURLTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/activity/CustomTabTest.java
  app/src/androidTestWebview/java/org/mozilla/focus/screenshots/SettingsScreenshots.java
Labels: needs merge

#2500 String import 20180421-120610
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-ru/strings.xml
Labels: needs merge

#2503 Assign visibilityLifeCycleCallback Closes #2499
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
Labels: needs review

#2479 Fix IllegalAccessError in UrlInputFragment Closes #2417
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: needs review

#2514 String import 20180424-120641
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-cak/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-dsb/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-mix/strings.xml
  app/src/main/res/values-oc/strings.xml
  app/src/main/res/values-ta/strings.xml
  app/src/main/res/values-te/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
Labels: needs merge

#2520 String import 20180425-120732
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-bg/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-gu-rIN/strings.xml
  app/src/main/res/values-oc/strings.xml
  app/src/main/res/values-vi/strings.xml
Labels: needs merge

#2527 Block 3rd party cookies by default Closes #2521
  app/src/main/res/xml/settings.xml
Labels: needs review

#2530 For #2329 - Adds a parameter to the cancel probe to show the type 🌮
  app/src/main/java/org/mozilla/focus/menu/context/WebContextMenu.java
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: needs review

#2536 Observe Custom Tab Sessions with TelemetrySessionObserver Closes #2531
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
Labels: needs review

#2535 Do not block cookies by default Closes #2521
  app/src/main/res/xml/settings.xml
Labels: needs merge

#2548 Hide Keyboard after dismissing add custom url Closes #2011
  app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteAddFragment.kt
Labels: needs merge, needs review

#2541 Use setImageResource for security icon vectors Closes #2540
  app/src/main/java/org/mozilla/focus/popup/PopupUtils.kt
Labels: needs review

#2551 Add correct placeholder in lo strings ✌🏻
  app/src/main/res/values-lo/strings.xml
Labels: needs merge

#2559 String import 20180430-171347
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-az/strings.xml
  app/src/main/res/values-hy-rAM/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-kw/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
Labels: needs merge
