Repository mozilla-mobile/focus-android, pull requests merged in 2018-08, with the labels that each got.

#3034 Update app shortcut icon – Erase Closes #2990
  app/src/main/res/drawable-hdpi/ic_shortcut_erase.png
  app/src/main/res/drawable-xhdpi/ic_shortcut_erase.png
  app/src/main/res/drawable-xxhdpi/ic_shortcut_erase.png
  app/src/main/res/drawable-xxxhdpi/ic_shortcut_erase.png
  app/src/main/res/drawable/ic_shortcut_erase.xml
Labels: needs review

#3048 Ensure title isn't empty in session view holder Closes #3047
  app/src/main/java/org/mozilla/focus/session/ui/SessionViewHolder.kt
Labels: needs merge

#3054 Update Menu SVG and remove Request Desktop Icon (cuts off) Closes #3032
  app/src/main/java/org/mozilla/focus/menu/browser/BrowserMenuAdapter.kt
  app/src/main/java/org/mozilla/focus/menu/browser/MenuItemViewHolder.java
  app/src/main/res/drawable/ic_add_to_home_menu_item.xml
  app/src/main/res/drawable/ic_device_desktop.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_open_in.xml
  app/src/main/res/drawable/ic_open_in_menu_item.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/ic_share_menu_item.xml
  app/src/main/res/layout/menu_blocking_switch.xml
  app/src/main/res/layout/request_desktop_check_menu_item.xml
Labels: needs review

#3058 Update GV to Beta 14 and add progress changed
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
  build.gradle
Labels: needs review

#2863 Issue #2854: Allow searches including a domain name
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: needs review

#3055 String import 20180803-120605
  app/src/main/res/values-te/strings.xml
Labels: needs merge

#3073 Fix manual A/B switcher so it can access Fretboard
  app/src/main/java/org/mozilla/focus/settings/ExperimentsSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/utils/Experiments.kt
Labels: needs merge

#3079 String import 20180807-121059
  app/src/main/res/values-en-rCA/strings.xml
  app/src/main/res/values-es-rMX/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-ur/strings.xml
Labels: needs merge

#3109 String import 20180812-120940
  app/src/main/res/values-trs/strings.xml
Labels: needs merge

#3106 Bumps version number
  app/build.gradle
Labels: needs review

#3116 Update to 62.0b16
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
  build.gradle
Labels: needs review

#3120 If progress is 100 declare page finished with GV
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
Labels: needs review

#3122 Clear Highlights for Find In Page GV Closes #3012
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java
Labels: needs review

#3123 No Issue: Update GV to Beta 62.0b17
  build.gradle
Labels: needs review

#3107 For #3075 - Adds telemetry for search suggestions
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsPreferences.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: needs review

#3132 Bump Gradle memory limit to 2GB
  gradle.properties
Labels: needs review

#3134 Revert "Remove permission limited to system apps"
  app/src/debug/AndroidManifest.xml
Labels: needs review

#3143 Fixes #3127 - Catches search suggestion parser error
  app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsFetcher.kt
Labels: needs review

#3138 Follow minimum tap target guidelines for FIP Closes #3019
  app/src/main/res/drawable/ic_arrowhead_down.xml
  app/src/main/res/drawable/ic_arrowhead_up.xml
  app/src/main/res/layout/find_in_page.xml
Labels: needs merge

#3136 Update Home Icon Closes #3130
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_device_desktop.xml
  app/src/main/res/drawable/ic_fingerprint.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_internet.xml
  app/src/main/res/drawable/ic_language.xml
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/ic_menu_info.xml
  app/src/main/res/drawable/ic_mozilla.xml
  app/src/main/res/drawable/ic_reorder.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/ic_tab_new.xml
  app/src/main/res/drawable/ic_trackers_blocked.xml
  app/src/main/res/drawable/ic_tracking_protection_disabled.xml
  app/src/main/res/drawable/images_removal_warning_background.xml
Labels: needs merge

#3133 Match styling in download and image context menus Closes #3128
  app/src/main/java/org/mozilla/focus/menu/context/WebContextMenu.java
  app/src/main/res/drawable/dialog_warning_background.xml
  app/src/main/res/layout/add_to_homescreen.xml
  app/src/main/res/layout/context_menu.xml
  app/src/main/res/layout/download_dialog.xml
  app/src/main/res/values/colors.xml
Labels: needs review

#3145 Fixes #3085 - Nests search suggestions in a scrollview
  app/src/main/res/layout/fragment_search_suggestions.xml
Labels: needs review

#3156 No issue: update GV Beta to 62.0b18
  build.gradle
Labels: needs review

#3165 Make Telemetry Setting Editable Closes #3121
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/widget/TelemetrySwitchPreference.kt
  app/src/main/res/xml/privacy_security_settings.xml
Labels: needs review

#3172 Add TYPE_TEXT_FLAG_NO_SUGGESTIONS to UrlView Closes #778
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: needs review

#3182 No Issue: Update to Beta 62.0b19
  build.gradle
Labels: needs review, review

#3159 Closes #2843 Reuse GeckoSession for switching tabs
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
Labels: needs review, review

#3188 Adds new locales for 7.0
  app/src/main/java/org/mozilla/focus/widget/LocaleListPreference.java
  tools/l10n/android2po/env.py
  tools/l10n/locales.py
Labels: needs review, review

#3180 String import 20180821-153013
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-az/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cak/strings.xml
  app/src/main/res/values-cy/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-dsb/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en-rCA/strings.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rCL/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-gl/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-kab/strings.xml
  app/src/main/res/values-kk/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mix/strings.xml
  app/src/main/res/values-mr/strings.xml
  app/src/main/res/values-ms/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-nn-rNO/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-te/strings.xml
  app/src/main/res/values-th/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-trs/strings.xml
  app/src/main/res/values-tsz/strings.xml
  app/src/main/res/values-tt/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: needs merge, review

#3196 No Issue: Disable GeckoView Restore Session
  app/src/main/java/org/mozilla/focus/fragment/WebFragment.java
  app/src/main/java/org/mozilla/focus/session/SessionManager.java
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
Labels: needs review, review

#3193 Closes #3174: Do not release aarch64 APKs.
  .taskcluster.yml
Labels: review

#3186 Closes #3152 add dismiss view top margin in url bar
  app/src/main/res/layout/fragment_urlinput.xml
Labels: needs review, review

#3200 String import 20180823-120514
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-ixl/strings.xml
  app/src/main/res/values-jv/strings.xml
  app/src/main/res/values-mr/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-pai/strings.xml
  app/src/main/res/values-ppl/strings.xml
  app/src/main/res/values-quc/strings.xml
  app/src/main/res/values-su/strings.xml
Labels: needs merge, review

#3204 Fixes #3168 - Styles modal dialogs 🔄
  app/src/main/res/values/styles.xml
Labels: review

#3212 No Issue - Adds new screenshot locale
  tools/l10n/locales.py
Labels: needs review, review

#3215 Allow blocking switch text to wrap Closes #3195
  app/src/main/res/layout/menu_blocking_switch.xml
Labels: needs review, review

#3208 Fixes #3192 - Adds a shortcut to render homescreen tips
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
Labels: review

#3203 Fix #3147 : allow Focus to be installed from Samsung AppStore
  app/src/main/AndroidManifest.xml
Labels: P1

#3211 String import 20180824-121135
  app/src/main/res/values-bo/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-mr/strings.xml
  app/src/main/res/values-th/strings.xml
Labels: needs merge, review

#3216 No issue: update to GV 62.0b20
  build.gradle
Labels: needs review, review

#3160 Fix #3098 : correct the sourceSets for different build variants
  app/build.gradle
  app/src/focusNightly/res/xml-v25/shortcuts.xml
  app/src/klarNightly/res/xml-v25/shortcuts.xml
Labels: P1, needs review

#3218 Fixes #3213 - Adds information for custom locales
  tools/l10n/android2po/env.py
Labels: review

#3219 No issue: add CODEOWNERS file.
  CODEOWNERS
Labels: review

#3228 String import 20180827-163032
  app/src/main/res/values-bo/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-es-rAR/strings.xml
  app/src/main/res/values-es-rMX/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-hus/strings.xml
  app/src/main/res/values-ka/strings.xml
  app/src/main/res/values-kab/strings.xml
  app/src/main/res/values-mix/strings.xml
  app/src/main/res/values-oc/strings.xml
  app/src/main/res/values-pai/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-th/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-yua/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: needs merge, review

#3225 Issue #3190: Convert activities from Java to Kotlin.
  app/src/main/java/org/mozilla/focus/activity/CustomTabActivity.kt
  app/src/main/java/org/mozilla/focus/activity/EraseShortcutActivity.java
  app/src/main/java/org/mozilla/focus/activity/EraseShortcutActivity.kt
  app/src/main/java/org/mozilla/focus/activity/InstallFirefoxActivity.java
  app/src/main/java/org/mozilla/focus/activity/InstallFirefoxActivity.kt
  app/src/main/java/org/mozilla/focus/activity/MainActivity.java
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/activity/TextActionActivity.java
  app/src/main/java/org/mozilla/focus/activity/TextActionActivity.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java
  app/src/main/java/org/mozilla/focus/open/InstallBannerViewHolder.java
Labels: review

#3241 Set vector icons dynamically Closes #3209
  app/src/main/java/org/mozilla/focus/session/ui/SessionViewHolder.kt
  app/src/main/java/org/mozilla/focus/widget/FloatingSessionsButton.java
  app/src/main/res/layout/fragment_browser.xml
Labels: needs review, review

#3242 Fixes #3205 #3224 - Fixes strings to add a linebreak programatically
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/res/values/strings.xml
Labels: review

#3244 Fixes #3233 #3238 URL Input Fragment Flickering
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/res/layout/fragment_urlinput.xml
Labels: needs merge

#3247 Update to use GECKOVIEW_62_RELBRANCH Closes #3246
  app/build.gradle
  build.gradle
Labels: needs merge

#3251 Closes #3046 Cancel Fragment Animations in onPause
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/locale/LocaleAwareFragment.java
Labels: needs review, review

#3252 Fixes #3059 - Accept license for latest sdk / build tools
  .taskcluster.yml
  tools/docker/Dockerfile
  tools/taskcluster/lib/tasks.py
  tools/taskcluster/schedule-master-build.py
  tools/taskcluster/schedule-screenshots.py
Labels: review

#3260 Fixes #3258: Tips without deep links are underlined
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: needs merge, review

#3261 Fixes #3250 - Adds the ace locale
  tools/l10n/android2po/env.py
  tools/l10n/locales.py
Labels: review

#3262 Closes #3248 Override Kotlin variables with getter
  app/src/main/java/org/mozilla/focus/activity/CustomTabActivity.kt
Labels: needs review, review

#3266 Closes #3263: Tip telemetry needs updated
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: review

#3267 Closes #3265: Tips should all be clickable
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
Labels: review
