Repository mozilla-mobile/focus-android, pull requests merged in 2018-10, with the labels that each got.

#3537 BrowserFragment: Use isCustomTab() instead of checking source.
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: review

#3535 String import 20181001-130701
  app/src/main/res/values-ro/strings.xml
Labels: needs merge, review

#3538 Closes #3531: BrowserFragment: Use single Observer and initialize views from current state.
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: review

#3534 Fixes #3522 Info Icon in Menu Blocking Switch misplaced
  app/src/main/res/layout/menu_blocking_switch.xml
Labels: needs merge, review

#3536 Closes #3523 Set All Fields of Session Security Info in onPageFinished
  app/src/main/java/org/mozilla/focus/session/SessionCallbackProxy.kt
  app/src/main/java/org/mozilla/focus/webview/FocusWebViewClient.java
Labels: needs merge, review

#3533 Closes #3529 Open Rights and About pages from Settings with InfoActivity
  app/src/main/java/org/mozilla/focus/settings/MozillaSettingsFragment.kt
Labels: review

#3543 Fixes #2194 - Add support for new GeckoView pin-to-screen API
  app/src/main/java/org/mozilla/focus/gecko/NestedGeckoView.java
Labels: P1

#3541 Fixes #3507 Do not process Session intents from MainActivity ✌🏻
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
Labels: review

#3545 For #3506 - Changes the separator when reporting active experiment names
  app/src/main/java/org/mozilla/focus/utils/Experiments.kt
Labels: review

#3546 No issue: Update to GV 62 Rel Branch from 10.1.2018
  build.gradle
Labels: review

#3539 Fixes #3496 Adds Build Type Tag (Release/Nightly) to Sentry 😋
  app/src/main/java/org/mozilla/focus/telemetry/SentryWrapper.kt
Labels: review

#3548 No issue: Fixes regression where all tabs opened in background
  app/src/main/java/org/mozilla/focus/menu/context/WebContextMenu.kt
Labels: review

#3549 Issue #3505: IntentProcessor: Do not select custom tab sessions.
  app/src/main/java/org/mozilla/focus/session/IntentProcessor.kt
Labels: review

#3557 String import 20181003-120813
  app/src/main/res/values-ro/strings.xml
Labels: needs merge, review

#3554 No issue: losslessly optimize image assets.
  app/src/main/res/drawable-nodpi/ic_search_engine_shape.png
  app/src/nightly/res/mipmap-hdpi/icon_background.png
  app/src/nightly/res/mipmap-xhdpi/ic_launcher.png
  app/src/nightly/res/mipmap-xhdpi/icon_background.png
  app/src/nightly/res/mipmap-xxhdpi/ic_launcher.png
  app/src/nightly/res/mipmap-xxhdpi/icon_background.png
  app/src/nightly/res/mipmap-xxxhdpi/icon_background.png
Labels: review

#3559 Update the locator for the context menu item in UI screenshot test script 🔃🔃
  app/src/androidTest/java/org/mozilla/focus/screenshots/BrowserScreenScreenshots.java
Labels: review

#3555 Enable WebViewDataTest.java for Klar build
  app/src/androidTest/java/org/mozilla/focus/privacy/WebViewDataTest.java
Labels: review

#3569 String import 20181005-120821
  app/src/main/res/values-ace/strings.xml
  app/src/main/res/values-ppl/strings.xml
Labels: needs merge, review

#3571 Fixes #3563 Remove all sessions with fingerprint unlock "new session"
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: review

#3567 for #3566 - Fixes Biometric crashing on some devices
  app/src/main/java/org/mozilla/focus/biometrics/Biometrics.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/settings/PrivacySecuritySettingsFragment.kt
Labels: review

#3576 For #2901 - Posts starting the foreground service
  app/src/main/java/org/mozilla/focus/session/SessionNotificationService.kt
Labels: review

#3577 String import 20181006-121146
  app/src/main/res/values-ppl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
Labels: needs merge, review

#3590 For #2901 - Reverts to use only startService
  app/src/main/java/org/mozilla/focus/session/SessionNotificationService.kt
Labels: review

#3588 Issue #3560: Update security icon after page has loaded.
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: review

#3594 Use new artifact names for Android components from maven.mozilla.org.
  app/build.gradle
Labels: review

#3595 String import 20181009-120853
  app/src/main/res/values-ace/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-kw/strings.xml
  app/src/main/res/values-ro/strings.xml
Labels: needs merge, review

#3591 Fixes #3564 - Send Search Privately Intent to IntentReceiverActivity
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/activity/TextActionActivity.kt
  app/src/main/java/org/mozilla/focus/session/IntentProcessor.kt
Labels: review

#3613 Update gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: review

#3600 Fixes #3593 Open Help + Privacy Tabs Selected
  app/src/main/java/org/mozilla/focus/settings/MozillaSettingsFragment.kt
Labels: review

#3575 Disable uploading of Focus Release to Nimbledroid
  tools/taskcluster/schedule-master-build.py
  tools/taskcluster/upload_apk_nimbledroid.py
Labels: review

#3611 Closes #3477: Add telemetry to new default browser prompt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/widget/DefaultBrowserPreference.java
Labels: review

#3631 Closes #3629: Compile UI tests on TaskCluster pull requests.
  .taskcluster.yml
Labels: review

#3615 String import 20181011-120950
  app/src/main/res/values-ace/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
Labels: needs merge, review

#3637 Revert Gradle changes and update Gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: review

#3649 Fix Queue args after taskcluster 5.0.0 breaking API release.
  tools/taskcluster/release.py
  tools/taskcluster/schedule-master-build.py
  tools/taskcluster/schedule-screenshots.py
Labels: review

#3650 String import 20181016-121918
  app/src/main/res/values-bo/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-meh/strings.xml
  app/src/main/res/values-pa-rIN/strings.xml
  app/src/main/res/values-ro/strings.xml
Labels: needs merge, review

#3644 Closes #3633 - Do not use onPageStart for source of URL in GV
  app/src/main/java/org/mozilla/focus/session/SessionCallbackProxy.kt
Labels: review

#3654 Fix Taskcluster rootUrl
  tools/taskcluster/release.py
  tools/taskcluster/schedule-master-build.py
  tools/taskcluster/schedule-screenshots.py
Labels: review

#3656 Fix API url for taskcluster-client calls.
  tools/taskcluster/release.py
  tools/taskcluster/schedule-master-build.py
  tools/taskcluster/schedule-screenshots.py
Labels: review

#3657 No issue: Update to A-C 0.27.0
  build.gradle
Labels: review

#3660 Closes #3642: Application restarts when interrupted
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/activity/TextActionActivity.kt
Labels: review

#3658 Closes #3630 - Adds pre-push hook and update read me
  README.md
  quality/pre-push-recommended.sh
Labels: review

#3667 Fixes #3664 - Check if security host is empty and show URL
  app/src/main/java/org/mozilla/focus/popup/PopupUtils.kt
Labels: review

#3668 Fixes #3625: Crash when saving custom search engine
  app/src/main/java/org/mozilla/focus/search/RadioSearchEngineListPreference.kt
Labels: review

#3639 Closes #3638: implement parallel UI test execution
  tools/taskcluster/execute-firebase-test.sh
  tools/taskcluster/execute-firebase-tests.sh
  tools/taskcluster/flank-conf-geckoview-arm.yml
  tools/taskcluster/flank-conf-geckoview-x86.yml
  tools/taskcluster/flank-conf-webview-arm.yml
  tools/taskcluster/flank-conf-webview-x86.yml
  tools/taskcluster/schedule-master-build.py
Labels: review

#3634 Bug 1486089 - Enable full Chain of Trust on nightly and github-releases
  .taskcluster.yml
  tools/taskcluster/lib/tasks.py
  tools/taskcluster/release.py
  tools/taskcluster/schedule-master-build.py
  tools/taskcluster/schedule-nightly-graph.py
Labels: review

#3651 Bug 1492245 - part 1: Sign nighlies with autograph
  .taskcluster.yml
  tools/taskcluster/lib/tasks.py
  tools/taskcluster/release.py
Labels: review

#3672 Closes #3605 - Check if nextAnim exists
  app/src/main/java/org/mozilla/focus/locale/LocaleAwareFragment.java
Labels: review

#3669 Fixes #3607 - Check if activity is finishing before showing prompt
  app/src/main/java/org/mozilla/focus/gecko/GeckoViewPrompt.java
Labels: review

#3681 schedule-nightly-graph.py: Fix bad rebase
  tools/taskcluster/schedule-nightly-graph.py
Labels: review

#3682 Fix quoting and html bug for hus
  app/src/main/res/values-hus/strings.xml
Labels: review

#3683 Revert "Closes #3642: Application restarts when interrupted"
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/activity/TextActionActivity.kt
Labels: review

#3688 Closes #3309 - Reenable Safe Browsing for GV
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
Labels: review

#3696 String import 20181020-120824
  app/src/main/res/values-bo/strings.xml
  app/src/main/res/values-ppl/strings.xml
Labels: needs merge, review

#3695 Fixes #3624 - Make MainActivity parent to SettingsActivity
  app/src/main/AndroidManifest.xml
Labels: review

#3692 Closes #3643 - Add Setting for Safe Browsing
  app/src/main/java/org/mozilla/focus/settings/SafeBrowsingSwitchPreference.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
  app/src/main/java/org/mozilla/focus/web/ClassicWebViewProvider.java
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/privacy_security_settings.xml
Labels: review

#3703 Closes #3702: Fix apk path in UI test tool conf
  tools/taskcluster/flank-conf-geckoview-arm.yml
  tools/taskcluster/flank-conf-geckoview-x86.yml
  tools/taskcluster/flank-conf-webview-arm.yml
  tools/taskcluster/flank-conf-webview-x86.yml
Labels: review

#3708 Closes #3707: Fix UI test path
  tools/taskcluster/execute-firebase-tests.sh
Labels: review

#3714 String import 20181023-121040
  app/src/main/res/values-anp/strings.xml
  app/src/main/res/values-ro/strings.xml
Labels: needs merge, review

#3704 add uploading of GV_Example apk
  tools/taskcluster/upload_apk_nimbledroid.py
Labels: review

#3722 Closes #3685 - Don't update security during download with GV
  app/src/main/java/org/mozilla/focus/session/SessionCallbackProxy.kt
Labels: review

#3706 For #3556 - Fixes WebViewDataTest to work with GeckoView
  app/src/androidTest/assets/test.html
  app/src/androidTest/java/org/mozilla/focus/privacy/WebViewDataTest.java
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
Labels: review

#3715 Fixes #3713: Browser UI is displayed in other apps
  app/src/main/java/org/mozilla/focus/activity/IntentReceiverActivity.kt
Labels: review

#3726 Closes #3725: Add more absolute paths for UI test job conf files
  tools/taskcluster/execute-firebase-tests.sh
  tools/taskcluster/flank-conf-geckoview-arm.yml
  tools/taskcluster/flank-conf-geckoview-x86.yml
  tools/taskcluster/flank-conf-webview-arm.yml
  tools/taskcluster/flank-conf-webview-x86.yml
Labels: review

#3553 Code clean
  app/build.gradle
  app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/ChangeSearchEngineTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/PullDownToRefreshTest.java
  app/src/androidTest/java/org/mozilla/focus/helpers/WebViewFakeLongPress.java
  app/src/androidTest/java/org/mozilla/focus/privacy/LocalSessionStorageTest.java
  app/src/androidTest/java/org/mozilla/focus/privacy/WebViewDataTest.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/BrowserScreenScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/ErrorPagesScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/FirstRunScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/SettingsScreenshots.java
  app/src/main/java/org/mozilla/focus/customtabs/CustomTabsService.java
  app/src/main/java/org/mozilla/focus/fragment/AddToHomescreenDialogFragment.java
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/FirstrunFragment.kt
  app/src/main/java/org/mozilla/focus/gecko/GeckoViewPrompt.java
  app/src/main/java/org/mozilla/focus/locale/LocaleManager.java
  app/src/main/java/org/mozilla/focus/open/OpenWithFragment.java
  app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsViewModel.kt
  app/src/main/java/org/mozilla/focus/utils/Browsers.java
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/java/org/mozilla/focus/utils/UrlUtils.java
  app/src/main/java/org/mozilla/focus/webview/FocusWebViewClient.java
  app/src/main/java/org/mozilla/focus/webview/matcher/BlocklistProcessor.java
  app/src/main/java/org/mozilla/focus/webview/matcher/EntityList.java
  app/src/main/java/org/mozilla/focus/webview/matcher/UrlMatcher.java
  app/src/main/java/org/mozilla/focus/widget/LocaleListPreference.java
  app/src/main/res/layout/custom_tab_menu_item.xml
  app/src/main/res/layout/fragment_urlinput.xml
  app/src/main/res/layout/menu_blocking_switch.xml
  app/src/main/res/layout/menu_item.xml
  app/src/main/res/layout/menu_whatsnew.xml
  app/src/main/res/menu/menu_search_engine_manual_add.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/focus/utils/UrlUtilsTest.java
Labels: review

#3727 No Issue - Update Android Components
  build.gradle
Labels: review

#3729 Closes #3728 - Adds Locale Language Tag to Sentry Tags
  app/src/main/java/org/mozilla/focus/telemetry/SentryWrapper.kt
Labels: review

#3732 Closes #3731: Add wget param to UI test script to fix taskcluster job
  tools/taskcluster/execute-firebase-tests.sh
Labels: review

#3734 String import 20181024-120840
  app/src/main/res/values-hus/strings.xml
  app/src/main/res/values-jv/strings.xml
  app/src/main/res/values-ppl/strings.xml
Labels: needs merge, review

#3736 Closes #3735: Add env var for google app cred path for UI tests
  tools/taskcluster/execute-firebase-tests.sh
Labels: review

#3737 Fixes #3733 - Add correct fragment tag on first run
  app/src/main/java/org/mozilla/focus/fragment/FirstrunFragment.kt
Labels: review

#3743 Closes #3742: Save UI test parallel result reports to test_artifacts
  .taskcluster.yml
  tools/taskcluster/execute-firebase-tests.sh
Labels: review

#3741 Closes #3740 - Updates Safe Browsing Strings
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/privacy_security_settings.xml
Labels: review

#3750 Fixes #3609: Crash on loading locales on slow phones
  app/src/main/java/org/mozilla/focus/settings/GeneralSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/widget/LocaleListPreference.java
Labels: review

#3739 Closes #3738 - Older Devices Do Not Restore GV History
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
Labels: review

#3756 Closes #3748 - Remove Safe Browsing Setting for WebView
  app/src/main/java/org/mozilla/focus/settings/PrivacySecuritySettingsFragment.kt
  app/src/main/java/org/mozilla/focus/web/ClassicWebViewProvider.java
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/privacy_security_settings.xml
Labels: review

#3758 Closes #3757: Add UI test reports to test artifacts
  .taskcluster.yml
Labels: review

#3755 Closes #3744 - Create SessionManager Extension to Close GeckoSessions
  app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityFirstrunTestRule.java
  app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityFirstrunTestRule.kt
  app/src/main/java/org/mozilla/focus/activity/CustomTabActivity.kt
  app/src/main/java/org/mozilla/focus/activity/EraseAndOpenShortcutActivity.kt
  app/src/main/java/org/mozilla/focus/activity/EraseShortcutActivity.kt
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/session/SessionManagerExtension.kt
  app/src/main/java/org/mozilla/focus/session/SessionNotificationService.kt
  app/src/main/java/org/mozilla/focus/session/ui/EraseViewHolder.kt
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
Labels: review

#3771 Closes #3770: Fix taskcluster exitcode
  tools/taskcluster/execute-firebase-tests.sh
Labels: review

#3761 Fixes GV Result
  app/src/main/java/org/mozilla/focus/gecko/GeckoViewPrompt.java
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
Labels: review

#3768 String import 20181026-120904
  app/src/main/res/values-bo/strings.xml
Labels: needs merge, review

#3762 Closes #3749 - Add Setting to Block Third Party Tracker Cookies with GV
  app/src/main/java/org/mozilla/focus/settings/PrivacySecuritySettingsFragment.kt
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_references.xml
Labels: review

#3774 Closes #3766 - Homescreen intents should send to IntentReceiverActivity
  app/src/main/java/org/mozilla/focus/shortcut/HomeScreen.java
Labels: review

#3775 Use clientID for Fretboard
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: review

#3777 For #3074 #957 - Adds strings for TP Whitelist and Crash reporting
  app/src/main/res/values/strings.xml
Labels: review

#3779 No Issue - Revert back to GV 63
  app/src/main/java/org/mozilla/focus/gecko/GeckoViewPrompt.java
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
  build.gradle
Labels: review

#3781 No Issue - Adds nv to env.py
  tools/l10n/android2po/env.py
Labels: review

#3778 Closes #3754 - Only Select Normal Browsing Sessions
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
Labels: review

#3791 Fixes #3789: Crash on the language menu
  app/src/main/java/org/mozilla/focus/widget/LocaleListPreference.java
Labels: review

#3783 Simplify enum
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: review

#3795 Closes #3790 - Load Initial URL sooner for GV
  app/src/main/java/org/mozilla/focus/fragment/WebFragment.kt
Labels: review

#3799 For #3797 - Adds the sn locale
  tools/l10n/locales.py
Labels: review

#3798 For mozilla-l10n/focus-android-l10n#42 - Fixes comments for l10n
  app/src/main/res/values/strings.xml
Labels: review

#3802 String import 20181029-204253
  app/src/main/res/values-bo/strings.xml
  app/src/main/res/values-nv/strings.xml
  app/src/main/res/values-ppl/strings.xml
  app/src/main/res/values-sn/strings.xml
Labels: needs merge, review

#3801 Update URLAutocompleteTest.java to accommodate UI change
  app/src/androidTest/java/org/mozilla/focus/activity/URLAutocompleteTest.java
Labels: review

#3803 Handle Android file permission dialog if it pops up
  app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/ImageSelectTest.java
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.java
Labels: review

#3805 Closes #3787 - App Name not displayed in Settings
  app/src/main/java/org/mozilla/focus/settings/PrivacySecuritySettingsFragment.kt
Labels: review

#3810 String import 20181030-120815
  app/src/main/res/values-cak/strings.xml
  app/src/main/res/values-cy/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-in/strings.xml
  app/src/main/res/values-ms/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: needs merge, review

#3814 Closes #3813 - Do Not Break Old Shortcut Intents
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/shortcut/HomeScreen.java
Labels: review

#3776 Closes #3753 - Show Option to Open in Focus in Custom Tab Context Menu
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/menu/context/WebContextMenu.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/res/menu/menu_browser_context.xml
Labels: review
