Repository mozilla-mobile/focus-android, pull requests merged in 2019-01, with the labels that each got.

#4103 Fix versionName in Nightly
  app/build.gradle
Labels: review

#4104 Fixes #4065: Variable i gets reset to 0
  app/src/main/java/org/mozilla/focus/webview/FocusWebViewClient.java
Labels: review

#4107 Closes #4058: Updates strings for trackers & learn more color
  app/src/main/java/org/mozilla/focus/settings/LearnMoreSwitchPreference.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/privacy_security_settings.xml
Labels: review

#4106 Fixes #4068: Wraps menu item text
  app/src/main/java/org/mozilla/focus/menu/browser/MenuItemViewHolder.java
  app/src/main/java/org/mozilla/focus/menu/browser/RequestDesktopCheckItemViewHolder.kt
  app/src/main/res/layout/menu_blocking_switch.xml
Labels: review

#4111 Closes #3921 - Show Snackbar after page load after toggling block toggle
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/menu/browser/BlockingItemViewHolder.kt
  app/src/main/java/org/mozilla/focus/menu/browser/BrowserMenu.java
  app/src/main/java/org/mozilla/focus/menu/browser/BrowserMenuAdapter.kt
  app/src/main/res/values/strings.xml
Labels: review

#4092 Closes #2452: New cookie descriptions
  app/src/main/java/org/mozilla/focus/settings/PrivacySecuritySettingsFragment.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_references.xml
Labels: review

#4118 Pre-land 9.0 strings for export
  app/src/main/res/values/strings.xml
Labels: review

#4091 Bug 1517732 - Expose routes.statuses because taskcluster-github now a…
  .taskcluster.yml
Labels: review

#4101 Adds "arrow" as a python dependency
  tools/docker/Dockerfile
Labels: review

#4100 Closes #4097 - Load new tips if locale has changed
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
Labels: review

#4096 convert widget classes to Kotlin
  app/src/main/java/org/mozilla/focus/widget/AboutPreference.java
  app/src/main/java/org/mozilla/focus/widget/AboutPreference.kt
  app/src/main/java/org/mozilla/focus/widget/MozillaPreference.java
  app/src/main/java/org/mozilla/focus/widget/MozillaPreference.kt
  app/src/main/java/org/mozilla/focus/widget/ResizableKeyboardCoordinatorLayout.java
  app/src/main/java/org/mozilla/focus/widget/ResizableKeyboardCoordinatorLayout.kt
  app/src/main/java/org/mozilla/focus/widget/ResizableKeyboardLinearLayout.java
  app/src/main/java/org/mozilla/focus/widget/ResizableKeyboardLinearLayout.kt
Labels: review

#4079 convert tests written in Java to Kotlin
  app/src/test/java/org/mozilla/focus/animation/TransitionDrawableGroupTest.java
  app/src/test/java/org/mozilla/focus/animation/TransitionDrawableGroupTest.kt
  app/src/test/java/org/mozilla/focus/locale/LocalesTest.java
  app/src/test/java/org/mozilla/focus/locale/LocalesTest.kt
  app/src/test/java/org/mozilla/focus/shortcut/HomeScreenTest.java
  app/src/test/java/org/mozilla/focus/shortcut/HomeScreenTest.kt
  app/src/test/java/org/mozilla/focus/utils/UrlUtilsTest.java
  app/src/test/java/org/mozilla/focus/utils/UrlUtilsTest.kt
  app/src/test/java/org/mozilla/focus/web/DownloadTest.java
  app/src/test/java/org/mozilla/focus/web/DownloadTest.kt
Labels: review

#4126 Adds comments to resolve mozilla-l10n/focus-android-l10n#45
  app/src/main/res/values/strings.xml
Labels: review

#4133 Fixes usage of a string that was renamed to be re-translated
  app/src/main/java/org/mozilla/focus/firstrun/FirstrunPagerAdapter.kt
Labels: review

#4128 Fixes telemetry documentation issues
  docs/Telemetry.md
Labels: review

#4130 Renames "build_*_task(...)" to "craft_*_task(...)"
  tools/taskcluster/lib/tasks.py
  tools/taskcluster/release.py
Labels: review

#4137 String import 20190115-121456
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-sl/strings.xml
Labels: needs merge, review

#4139 Update A-C version to 0.32.2
  build.gradle
Labels: review

#4108 Closes #3146 Uses Locale Independent Strings For Cookie Setting Value
  app/src/main/java/org/mozilla/focus/settings/PrivacySecuritySettingsFragment.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
  app/src/main/java/org/mozilla/focus/widget/CookiesPreference.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings_references.xml
  app/src/main/res/xml/privacy_security_settings.xml
Labels: review

#4149 String import 20190117-121133
  app/src/main/res/values-cak/strings.xml
  app/src/main/res/values-en-rGB/strings.xml
  app/src/main/res/values-es-rMX/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-mr/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-nn-rNO/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-th/strings.xml
Labels: needs merge, review

#4150 convert tests written in Java to Kotlin
  app/src/androidTest/java/org/mozilla/focus/activity/AccessAboutAndYourRightsPagesTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/AccessAboutAndYourRightsPagesTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.kt
Labels: review

#4147 Fixes #4125: Update to GeckoView Beta 65
  app/build.gradle
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.java
  app/src/androidTest/java/org/mozilla/focus/helpers/WebViewFakeLongPress.java
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/InfoFragment.kt
  app/src/main/java/org/mozilla/focus/menu/context/WebContextMenu.kt
  app/src/main/java/org/mozilla/focus/session/SessionCallbackProxy.kt
  app/src/main/java/org/mozilla/focus/web/GeckoWebViewProvider.kt
  app/src/main/java/org/mozilla/focus/web/IWebView.java
  app/src/main/java/org/mozilla/focus/webview/LinkHandler.java
  build.gradle
Labels: review

#4110 Closes #4105 Separate Erase All Fun For Just Erase Icon
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: review

#4151 Automation: Resolves issue with multiline string concatenation
  tools/taskcluster/release.py
Labels: review

#4153 String import 20190118-121136
  app/src/main/res/values-es-rMX/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-su/strings.xml
  app/src/main/res/values-th/strings.xml
  app/src/main/res/values-tsz/strings.xml
Labels: needs merge, review

#4163 Fixes #4155: Allow to disable Safe Browsing
  app/src/main/java/org/mozilla/focus/settings/PrivacySecuritySettingsFragment.kt
Labels: review

#4171 String import 20190122-121122
  app/src/main/res/values-dsb/strings.xml
  app/src/main/res/values-hsb/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-tr/strings.xml
Labels: needs merge, review

#4177 String import 20190123-121144
  app/src/main/res/values-es-rMX/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-ia/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
Labels: needs merge

#4178 convert test written in Java to Kotlin
  app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.kt
Labels: review

#4183 String import 20190124-122150
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-hi-rIN/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-sn/strings.xml
Labels: review
