Repository mozilla-mobile/focus-android, pull requests merged in 2021-08, with the labels that each got.

#5043 Issue #5013: InputToolbarIntegration: Do not switch to display mode after invoking commit listener.
  app/src/main/java/org/mozilla/focus/input/InputToolbarIntegration.kt
Labels: 🛬 needs landing

#5048 Set version to 93.0.
  app/build.gradle
Labels: 🛬 needs landing

#5047 Set version to 91.0.
  app/build.gradle
Labels: 🛬 needs landing

#5038 Issue #5023: UrlInputFragment: Hide keyboard on pause.
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: 🛬 needs landing

#5039 Update to Mozilla Android Components 92.0.20210730143121.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5049 For #5042 - Count total number of blocked trackers.
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/browser/BlockedTrackersMiddleware.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
Labels: 🛬 needs landing

#5036 Issue #5022: Tracking info icon: Use click handler that closes menu.
  app/src/main/java/org/mozilla/focus/menu/browser/BlockingItemViewHolder.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#5055 For #5054: Fix failing tests on nav bar
  app/src/androidTest/java/org/mozilla/focus/activity/SearchTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/HomeScreenScreenshots.java
Labels: 🛬 needs landing

#5062 Update Mozilla Android Components to 92.0.20210803190134
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5061 Update to Mozilla Android Components 91.0.11
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5066 For #4975 - Autolink local.properties helpers section
  settings.gradle
Labels: 🛬 needs landing

#5067 Closes #5020: Clear selected search suggetion from view model after processing.
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsViewModel.kt
Labels: 🛬 needs landing

#5083 For #4920,#5078, #5074, #5073: Fix menu locators in tests
  app/src/androidTest/java/org/mozilla/focus/activity/ThreeDotMainMenuTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/ThreeDotMainMenuRobot.kt
Labels: 🛬 needs landing

#5092 Update to Android-Components 92.0.20210809190134
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
  app/src/main/java/org/mozilla/focus/session/IntentProcessor.kt
  app/src/main/java/org/mozilla/focus/settings/LearnMoreSwitchPreference.kt
  app/src/main/java/org/mozilla/focus/settings/MozillaSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryMiddleware.kt
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5119 Update Android Components version to 93.0.20210812143121.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5117 For #5091: Add metropolis font.
  app/src/main/res/font/metropolis.xml
  app/src/main/res/font/metropolis_black.ttf
  app/src/main/res/font/metropolis_blackitalic.ttf
  app/src/main/res/font/metropolis_bold.ttf
  app/src/main/res/font/metropolis_bolditalic.ttf
  app/src/main/res/font/metropolis_extrabold.ttf
  app/src/main/res/font/metropolis_extrabolditalic.ttf
  app/src/main/res/font/metropolis_extralighitalic.ttf
  app/src/main/res/font/metropolis_extralight.ttf
  app/src/main/res/font/metropolis_light.ttf
  app/src/main/res/font/metropolis_lightitalic.ttf
  app/src/main/res/font/metropolis_medium.ttf
  app/src/main/res/font/metropolis_mediumitalic.ttf
  app/src/main/res/font/metropolis_regular.ttf
  app/src/main/res/font/metropolis_regularitalic.ttf
  app/src/main/res/font/metropolis_semibold.ttf
  app/src/main/res/font/metropolis_semibolditalic.ttf
  app/src/main/res/font/metropolis_thin.ttf
  app/src/main/res/font/metropolis_thinitalic.ttf
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#5118 For #4823: re-enabled browsing notification UI tests
  app/src/androidTest/java/org/mozilla/focus/activity/EraseBrowsingDataTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchContextTest.kt
Labels: eng:ui-test, 🛬 needs landing

#5124 Close #5120: Warm GeckoEngine first during app creation
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
Labels: 🛬 needs landing

#5095 Close #5084: Correct Custom Tab menu items
  app/build.gradle
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserMenuController.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/menu/ToolbarMenu.kt
  app/src/main/java/org/mozilla/focus/menu/browser/CustomTabMenu.kt
  app/src/test/java/org/mozilla/focus/menu/BrowserMenuControllerTest.kt
Labels: 🛬 needs landing

#5131 Update Android Components version to 93.0.20210813143343
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5135 Closes #5134: remove unnecessary coroutines proguard rules.
  app/proguard-rules.pro
Labels: 🛬 needs landing

#5137 Update trackers count note description.
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#5129 No issue: Pre-land strings for the design changes.
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#5143 Closes #5141: Remove FeatureFlags.isMvp
  app/src/androidTest/java/org/mozilla/focus/activity/EraseBrowsingDataTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/fragment/AddToHomescreenDialogFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/menu/home/HomeMenuAdapter.kt
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
  app/src/main/java/org/mozilla/focus/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/focus/utils/FeatureFlags.kt
  app/src/main/java/org/mozilla/focus/utils/ViewUtils.kt
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/layout/fragment_urlinput.xml
Labels: 🛬 needs landing

#5122 For #5102: use fast service loader via ProGuard.
  app/proguard-rules.pro
Labels: 🛬 needs landing

#5138 For #5108: Update search suggestions message and design.
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
  app/src/main/res/drawable/background_search_suggestion_section.xml
  app/src/main/res/layout/fragment_search_suggestions.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🛬 needs landing

#5151 Remove extra character from tip_request_desktop2 string.
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#5157 Add line break to tip_request_desktop2 string.
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#5153 Update Klar logo in splash screen
  app/src/focus/res/drawable-hdpi/wordmark.png
  app/src/focus/res/drawable-xhdpi/wordmark.png
  app/src/focus/res/drawable-xxhdpi/wordmark.png
  app/src/klar/res/drawable-hdpi/wordmark.png
  app/src/klar/res/drawable-hdpi/wordmark2.png
  app/src/klar/res/drawable-xhdpi/wordmark.png
  app/src/klar/res/drawable-xhdpi/wordmark2.png
  app/src/klar/res/drawable-xxhdpi/wordmark.png
  app/src/klar/res/drawable-xxhdpi/wordmark2.png
  app/src/klar/res/drawable/wordmark2.xml
  app/src/main/java/org/mozilla/focus/browser/LocalizedContent.kt
Labels: 🛬 needs landing

#5160 Temporarily remove whats new menu item
  app/src/main/java/org/mozilla/focus/menu/home/HomeMenuAdapter.kt
Labels: 🛬 needs landing

#5142 No issue: Use API 30 (Pixel 3) in contributor workflow
  .github/workflows/build-contributor-pr.yml
Labels: 🛬 needs landing

#5159 Adds support for window requests and app links
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/engine/AppContentInterceptor.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5167 Issue #5166: Update default Tracking Protection blocking resources
  app/src/main/java/org/mozilla/focus/engine/EngineSharedPreferencesListener.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/privacy_security_settings.xml
Labels: 🛬 needs landing

#5170 Update Android Components version to 93.0.20210818143126
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5136 For #5001 - Implement Shortcuts for Focus
  app/build.gradle
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserMenuController.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/home/HomeScreen.kt
  app/src/main/java/org/mozilla/focus/menu/ToolbarMenu.kt
  app/src/main/java/org/mozilla/focus/menu/browser/DefaultBrowserMenu.kt
  app/src/main/java/org/mozilla/focus/state/AppAction.kt
  app/src/main/java/org/mozilla/focus/state/AppReducer.kt
  app/src/main/java/org/mozilla/focus/state/AppState.kt
  app/src/main/java/org/mozilla/focus/topsites/DefaultTopSitesStorage.kt
  app/src/main/java/org/mozilla/focus/topsites/DefaultTopSitesView.kt
  app/src/main/java/org/mozilla/focus/topsites/TopSiteMenuItem.kt
  app/src/main/java/org/mozilla/focus/topsites/TopSites.kt
  app/src/main/res/layout/fragment_urlinput2.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/focus/menu/BrowserMenuControllerTest.kt
  app/src/test/java/org/mozilla/focus/topsites/DefaultTopSitesStorageTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#5178 Add context menu additional note as string
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#5179 For 5172: Update whats-new SUMO link.
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
Labels: 🛬 needs landing

#5139 Integrate AwesomeBar() composable from compose-awesomebar component.
  app/build.gradle
  app/src/androidTest/java/org/mozilla/focus/activity/SearchTest.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsFetcher.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsViewModel.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
  app/src/main/java/org/mozilla/focus/theme/FocusTheme.kt
  app/src/main/res/layout/fragment_search_suggestions.xml
  app/src/main/res/layout/item_suggestion.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#5187 Add androidTestUtil dependency for test orchestrator
  app/build.gradle
Labels: 🛬 needs landing

#5176 Update Focus logo
  app/src/focus/res/drawable-hdpi/wordmark2.png
  app/src/focus/res/drawable-xhdpi/wordmark2.png
  app/src/focus/res/drawable-xxhdpi/wordmark2.png
  app/src/main/res/drawable/wordmark2.xml
Labels: 🛬 needs landing

#5188 For 4931: Replace icons for tracking protection.
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/fragment/AddToHomescreenDialogFragment.kt
  app/src/main/java/org/mozilla/focus/settings/privacy/TrackingProtectionPanel.kt
  app/src/main/java/org/mozilla/focus/widget/SwitchWithDescription.kt
  app/src/main/res/drawable/ic_tracking_protection_disabled.xml
  app/src/main/res/drawable/ic_tracking_protection_disabled2.xml
  app/src/main/res/layout/dialog_tracking_protection_sheet.xml
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5175 Replace Focus icons with AC icons
  app/src/main/java/org/mozilla/focus/browser/BrowserMenuControllerAdapter.kt
  app/src/main/java/org/mozilla/focus/browser/integration/NavigationButtonsIntegration.kt
  app/src/main/java/org/mozilla/focus/menu/browser/BlockingItemViewHolder.kt
  app/src/main/java/org/mozilla/focus/menu/browser/BrowserMenu.kt
  app/src/main/java/org/mozilla/focus/menu/browser/BrowserMenuAdapter.kt
  app/src/main/java/org/mozilla/focus/menu/browser/BrowserMenuViewHolder.java
  app/src/main/java/org/mozilla/focus/menu/browser/CustomTabMenu.kt
  app/src/main/java/org/mozilla/focus/menu/browser/CustomTabMenuItemViewHolder.java
  app/src/main/java/org/mozilla/focus/menu/browser/DefaultBrowserMenu.kt
  app/src/main/java/org/mozilla/focus/menu/browser/MenuItemViewHolder.java
  app/src/main/java/org/mozilla/focus/menu/browser/NavigationItemViewHolder.java
  app/src/main/java/org/mozilla/focus/menu/browser/RequestDesktopCheckItemViewHolder.kt
  app/src/main/java/org/mozilla/focus/menu/home/HomeMenuAdapter.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
  app/src/main/java/org/mozilla/focus/shortcut/IconGenerator.kt
  app/src/main/res/drawable/ic_add_to_home_screen.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_clear.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_device_desktop.xml
  app/src/main/res/drawable/ic_forward.xml
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_menu_info.xml
  app/src/main/res/drawable/ic_open_in.xml
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_settings2.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/ic_share2.xml
  app/src/main/res/drawable/ic_stop.xml
  app/src/main/res/layout/connection_details.xml
  app/src/main/res/layout/menu_navigation.xml
  app/src/main/res/layout/request_desktop_check_menu_item.xml
  app/src/main/res/menu/menu_search_engine_manual_add.xml
Labels: 🛬 needs landing

#5186 For 5182: Add domain name as fallback to website title.
  app/src/main/java/org/mozilla/focus/ext/ContentState.kt
  app/src/main/java/org/mozilla/focus/ext/String.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5200 Add missing string for shortcuts tip
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#5198 For 5002: Add root domain as fallback to shortcut title.
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserMenuController.kt
Labels: 🛬 needs landing

#5205 No issue: Update Flank to v21.08.1
  tools/taskcluster/execute-firebase-tests.sh
Labels: 🛬 needs landing

#5207 Fix context menu additional note string
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#5208 Increment contextmenu_erased_images_note string
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#5211 Update Focus/Klar logos
  app/src/klar/res/drawable/wordmark2.xml
  app/src/main/res/drawable/wordmark2.xml
  app/src/main/res/layout/fragment_urlinput2.xml
Labels: 🛬 needs landing

#5184 For 5059: Add Glean metric for adding to autocomplete list from settings
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteAddFragment.kt
Labels: 🛬 needs landing

#5204 For 5172: Update whats-new SUMO link with stable topic.
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
Labels: 🛬 needs landing

#5213 For #5210: Update enhanced tracking protection strings.
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
  app/src/main/res/layout/add_to_homescreen.xml
  app/src/main/res/layout/dialog_add_to_homescreen2.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/privacy_security_settings.xml
Labels: 🛬 needs landing

#5214 For #5212: Use TwoStateButton for tablet toolbar buttons.
  app/src/main/java/org/mozilla/focus/browser/integration/NavigationButtonsIntegration.kt
Labels: 🛬 needs landing

#5189 For 5056: Add Telemetry for Shortcuts.
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserMenuController.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt
Labels: 🛬 needs landing

#5206 Implement tips section as a carousel
  app/src/androidTest/java/org/mozilla/focus/screenshots/HomeScreenScreenshots.java
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/tips/DotPagerIndicatorDecoration.kt
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
  app/src/main/java/org/mozilla/focus/tips/TipsAdapter.kt
  app/src/main/java/org/mozilla/focus/tips/TipsHorizontalCarousel.kt
  app/src/main/res/layout/fragment_urlinput2.xml
  app/src/main/res/layout/tip_carousel_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#5224 For #4927: Update settings fragments toolbar and statusbar colors.
  app/src/main/java/org/mozilla/focus/settings/BaseSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/settings/BaseSettingsLikeFragment.kt
  app/src/main/res/layout/fragment_autocomplete_add_domain.xml
  app/src/main/res/layout/fragment_autocomplete_customdomains.xml
  app/src/main/res/layout/fragment_exceptions_domains.xml
  app/src/main/res/values/colors.xml
Labels: 🛬 needs landing

#5256 Update to Mozilla Android Components 92.0.11.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5264 For #5240 add the SCRIPTS_AND_SUB_RESOURCES TrackingCategory by default
  app/src/main/java/org/mozilla/focus/engine/EngineSharedPreferencesListener.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/layout/dialog_tracking_protection_sheet.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/privacy_security_settings.xml
Labels: 🛬 needs landing

#5266 For #5240: Update default setting for trackers in panel.
  app/src/main/java/org/mozilla/focus/settings/privacy/TrackingProtectionPanel.kt
Labels: 🛬 needs landing

#5268 Attach SearchSuggestionsViewModel to UrlInputFragment instead of Activity
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
Labels: 🛬 needs landing

#5246 For #5243: Provide color for disabled state of preferences.
  app/src/main/res/color/preference_title_text.xml
  app/src/main/res/values/colors.xml
Labels: 🛬 needs landing

#5248 For #5241: Hide delete all websites button when in select mode.
  app/src/main/java/org/mozilla/focus/exceptions/ExceptionsListFragment.kt
Labels: 🛬 needs landing

#5242 For #5185: Refactor about page.
  app/src/main/java/org/mozilla/focus/fragment/AboutFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
  app/src/main/java/org/mozilla/focus/settings/MozillaSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/state/AppReducer.kt
  app/src/main/java/org/mozilla/focus/state/AppState.kt
  app/src/main/res/layout/fragment_about.xml
  app/src/main/res/xml/mozilla_settings.xml
Labels: 🛬 needs landing

#5274 For #5217: Remove Switch to link in new tab immediately preference.
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/xml/general_settings.xml
Labels: 🛬 needs landing

#5277 For #5276: Add whats new link for Klar build.
  app/src/main/java/org/mozilla/focus/settings/SettingsFragment.kt
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
Labels: 🛬 needs landing

#5275 For #5244: Switch places between the Refresh and Share menu buttons.
  app/src/main/java/org/mozilla/focus/menu/browser/DefaultBrowserMenu.kt
Labels: 🛬 needs landing

#5262 Issue #5216 - Display Shortcuts in the AwesomeBar
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/home/HomeScreen.kt
  app/src/main/java/org/mozilla/focus/input/InputToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
  app/src/main/java/org/mozilla/focus/topsites/TopSites.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#5231 For #5222: Handle colors for dark theme toolbar for tablets.
  app/src/main/java/org/mozilla/focus/browser/integration/NavigationButtonsIntegration.kt
Labels: 🛬 needs landing
