Repository mozilla-mobile/focus-android, pull requests merged in 2021-07, with the labels that each got.

#4966 Update Mozilla Android Components to 91.0.20210624190127.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#4971 Update Android Components to 91.0.20210705190256.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#4970 Use default endpoint for Glean
  app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt
Labels: 🛬 needs landing

#4951 Integrate browser-toolbar component.
  app/build.gradle
  app/src/androidTest/java/org/mozilla/focus/activity/ToggleBlockTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/URLExceptionTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/CustomTabRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SearchRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/EspressoHelper.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/AllowListScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/BrowserScreenScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/ErrorPagesScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/HomeScreenScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/NotificationScreenshots.java
  app/src/main/java/org/mozilla/focus/browser/BrowserMenuControllerAdapter.kt
  app/src/main/java/org/mozilla/focus/browser/DisplayToolbar.kt
  app/src/main/java/org/mozilla/focus/browser/binding/BlockingThemeBinding.kt
  app/src/main/java/org/mozilla/focus/browser/binding/LoadingBinding.kt
  app/src/main/java/org/mozilla/focus/browser/binding/MenuBinding.kt
  app/src/main/java/org/mozilla/focus/browser/binding/ProgressBinding.kt
  app/src/main/java/org/mozilla/focus/browser/binding/SecurityInfoBinding.kt
  app/src/main/java/org/mozilla/focus/browser/binding/ToolbarButtonBinding.kt
  app/src/main/java/org/mozilla/focus/browser/binding/UrlBinding.kt
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/browser/integration/NavigationButtonsIntegration.kt
  app/src/main/java/org/mozilla/focus/fragment/BaseFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/input/InputToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
  app/src/main/java/org/mozilla/focus/navigation/Navigator.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsViewModel.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
  app/src/main/java/org/mozilla/focus/state/AppAction.kt
  app/src/main/java/org/mozilla/focus/state/AppReducer.kt
  app/src/main/java/org/mozilla/focus/state/AppState.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/widget/AnimatedProgressBar.kt
  app/src/main/res/drawable/cursor.xml
  app/src/main/res/layout-sw600dp/toolbar.xml
  app/src/main/res/layout/browser_display_toolbar.xml
  app/src/main/res/layout/fragment_browser.xml
  app/src/main/res/layout/fragment_urlinput.xml
  app/src/main/res/layout/toolbar.xml
  docs/Telemetry.md
Labels: 🛬 needs landing

#4899 Migrate tp exceptions
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/components/EngineProvider.kt
  app/src/main/java/org/mozilla/focus/exceptions/GeckoExceptionsMigrator.kt
Labels: 🛬 needs landing

#4982 For #4974: fixes nav bar and menu locators IDs in UI tests
  app/src/androidTest/java/org/mozilla/focus/activity/EraseBrowsingDataTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/HomeScreenScreenshots.java
Labels: eng:ui-test, 🛬 needs landing

#4983 For #4934: fixes scrolling text into view
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsPrivacyMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#4984 No issue: Run UI tests on API28 for better stability on FTL
  app/src/androidTest/java/org/mozilla/focus/activity/ErrorPagesTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/AddToHomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/ThreeDotMainMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
  tools/taskcluster/flank.yml
Labels: eng:ui-test, 🛬 needs landing

#4978 Add Github Action checks for contributors
  .github/workflows/build-contributor-pr.yml
Labels: eng:ui-test, 🛬 needs landing

#4991 For #4825: Fixes search bar IDs and re-enables enableSearchSuggestion…
  app/src/androidTest/java/org/mozilla/focus/activity/SearchTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/HomeScreenRobot.kt
Labels: eng:ui-test, 🕵️‍♀️ needs review, 🛬 needs landing

#4997 For #4996: disables testVisitingMultipleSites UI test
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
Labels: eng:intermittent-test, eng:ui-test, 🕵️‍♀️ needs review, 🛬 needs landing

#4999 Change profile in build-contributor-pr.yml
  .github/workflows/build-contributor-pr.yml
Labels: 🛬 needs landing

#4956 Update splash screen alerts design
  app/src/androidTest/java/org/mozilla/focus/activity/EraseBrowsingDataTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
  app/src/main/java/org/mozilla/focus/utils/ViewUtils.kt
  app/src/main/res/drawable/background_snackbar.xml
  app/src/main/res/layout/focus_preference.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🛬 needs landing

#4963 Hide floating buttons when the keyboard is shown
  app/src/main/java/org/mozilla/focus/widget/ResizableKeyboardViewDelegate.java
  app/src/main/res/layout/fragment_browser.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/attrs.xml
Labels: 🛬 needs landing

#4989 Update loading progress bar gradient
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: 🛬 needs landing

#5005 Update FeaturesFlag.isMvp
  app/src/main/java/org/mozilla/focus/utils/FeatureFlags.kt
Labels: 🛬 needs landing

#4968 For #4967 - Record search / ads providers appearing in search results
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/telemetry/FactsProcessor.kt
  app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/test/java/org/mozilla/focus/telemetry/GleanMetricsServiceTest.kt
Labels: pr:needs-ac-bump, 🛬 needs landing

#4987 Update Focus background
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/res/drawable-land/dark_background.xml
  app/src/main/res/drawable/dark_background.xml
Labels: 🛬 needs landing

#5018 Update dependencies and set up Jetpack Compose.
  .github/workflows/build-contributor-pr.yml
  .taskcluster.yml
  app/build.gradle
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/activity/CustomTabActivity.kt
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteAddFragment.kt
  app/src/main/java/org/mozilla/focus/browser/integration/FullScreenIntegration.kt
  app/src/main/java/org/mozilla/focus/ext/String.kt
  app/src/main/java/org/mozilla/focus/firstrun/FirstrunPagerAdapter.kt
  app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/shortcut/IconGenerator.kt
  app/src/test/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsViewModelTest.kt
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/Dependencies.kt
  gradle/wrapper/gradle-wrapper.properties
  service-telemetry/build.gradle
  tools/docker/Dockerfile
  tools/taskcluster/lib/tasks.py
  tools/taskcluster/schedule-main-build.py
Labels: 🛬 needs landing

#5029 Use stable version of Jetpack Compose and related tooling/dependencies.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#5025 For #5011 - the GV icon was missing on the "About" page
  app/src/main/java/org/mozilla/focus/browser/LocalizedContent.kt
Labels: 🛬 needs landing

#5033 Issue #4990: BrowserFragment: Handle missing events.
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#4988 For #4975 - Build enhancements
  README.md
  app/build.gradle
  settings.gradle
Labels: 🛬 needs landing
