Repository mozilla-mobile/focus-android, pull requests merged in 2021-11, with the labels that each got.

#5754 No issue: Remove Firebase shippable secrets
  taskcluster/focus_android_taskgraph/transforms/build.py
Labels: 🛬 needs landing

#5715 For #5714: Update style for toolbar menu items.
  app/src/main/res/values/styles.xml
Labels: 🛬 needs landing

#5730 Issue 5572: Handle 'Open in Focus' case if tabs feature flag is disabled
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5725 For #5652: Migrate crash reporter telemetry.
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/fragment/CrashReporterFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: 🛬 needs landing

#5734 For #5630: Update powered by item colors.
  app/src/main/java/org/mozilla/focus/menu/browser/CustomTabMenu.kt
Labels: 🛬 needs landing

#5749 Update the source of known browsers
  app/src/main/java/org/mozilla/focus/activity/InstallFirefoxActivity.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetrySettingsProvider.kt
  app/src/main/java/org/mozilla/focus/utils/Browsers.java
  app/src/main/java/org/mozilla/focus/widget/DefaultBrowserPreference.kt
Labels: 🛬 needs landing

#5759 Update to first Android Components 96.0 Nightly build
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5764 For #5762: Use AppCompatResources to prevent crash
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: 🛬 needs landing

#5729 For #5728 integrate API for persistent tracking protection exceptions in private mode
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/exceptions/ExceptionDomains.kt
  app/src/main/java/org/mozilla/focus/exceptions/ExceptionMigrationMiddleware.kt
  app/src/main/java/org/mozilla/focus/exceptions/ExceptionsListFragment.kt
  app/src/main/java/org/mozilla/focus/exceptions/ExceptionsRemoveFragment.kt
  app/src/main/java/org/mozilla/focus/exceptions/GeckoExceptionsMigrator.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5756 Fix openCustomTabInFocusTest
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
Labels: 🛬 needs landing

#5766 Dismiss context menu at lateral tapping
  app/src/main/res/drawable/dialog_background_with_insets.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: 🛬 needs landing

#5638 Update screenshot tests and helpers
  app/src/androidTest/java/org/mozilla/focus/activity/FirstRunDialogueTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsSearchMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/ThreeDotMainMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/FirstRunScreenshots.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/HomeScreenScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/HomeScreenScreenshots.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/SettingsScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/SettingsScreenshots.kt
Labels: eng:ui-test, 🛬 needs landing

#5771 For #5261 - Avoid FLAG_ACTIVITY_NEW_TASK for the custom tab intent
  app/build.gradle
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
Labels: 🛬 needs landing

#5777 No issue: remove screenshots tests from Flank test-targets
  automation/taskcluster/androidTest/flank-x86.yml
Labels: eng:ui-test, 🛬 needs landing

#5690 Refactor UI kind and gradle config to support more UI tests
  .mergify.yml
  app/build.gradle
  taskcluster/ci/build/kind.yml
  taskcluster/ci/signing/kind.yml
  taskcluster/ci/ui-test/kind.yml
  taskcluster/focus_android_taskgraph/transforms/build.py
  taskcluster/focus_android_taskgraph/transforms/signing.py
Labels: 🛬 needs landing (squash)

#5782 Close #5781: Provide RustHttpConfig with a client
  app/build.gradle
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/experiments/NimbusSetup.kt
Labels: 🚀 needs uplift, 🛬 needs landing

#5792 For UI tests: Fix hardcoded app name in selectors
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsGeneralMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsMozillaMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#5797 For #5527: Add explicit color for share button.
  app/src/main/java/org/mozilla/focus/menu/browser/DefaultBrowserMenu.kt
Labels: 🛬 needs landing

#5810 Block autoplayAudible videos
  app/build.gradle
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5798 For #5794: Remove redundant accessibility announcement.
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5825 For #5623: Set transparent navigation bar on light theme.
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
Labels: 🛬 needs landing

#5758 For #5753: Migrate etp exceptions telemetry.
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/exceptions/ExceptionsListFragment.kt
  app/src/main/java/org/mozilla/focus/exceptions/ExceptionsRemoveFragment.kt
  app/src/main/java/org/mozilla/focus/settings/privacy/PrivacySecuritySettingsFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: 🛬 needs landing

#5769 For #5651: Migrate notification and launcher icon shortcuts telemetry.
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/activity/EraseAndOpenShortcutActivity.kt
  app/src/main/java/org/mozilla/focus/activity/EraseShortcutActivity.kt
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/session/SessionNotificationService.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: 🛬 needs landing

#5793 For #5785: Add telemetry for tabs count on app backgrounded.
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/biometrics/LockObserver.kt
Labels: 🛬 needs landing

#5689 Update automation account user in .taskcluster.yml
  .taskcluster.yml
Labels: 🛬 needs landing

#5826 No issue: Add focus custom typography.
  app/src/main/java/org/mozilla/focus/fragment/AboutFragment.kt
  app/src/main/java/org/mozilla/focus/home/HomeScreen.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
  app/src/main/java/org/mozilla/focus/topsites/TopSites.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusColors.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusTheme.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusTypography.kt
Labels: 🛬 needs landing

#5853 No issue: update steps in remove exception URLs tests
  app/src/androidTest/java/org/mozilla/focus/activity/EnhancedTrackingProtectionSettingsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SiteSecurityInfoSheetRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#5855 For #5851, #5547 Fix package names and remove long labels from shortcuts.
  app/src/focusBeta/res/xml-v25/shortcuts.xml
  app/src/focusNightly/res/xml-v25/shortcuts.xml
  app/src/klarBeta/res/xml-v25/shortcuts.xml
  app/src/klarDebug/res/xml-v25/shortcuts.xml
  app/src/klarNightly/res/xml-v25/shortcuts.xml
  app/src/klarRelease/res/xml-v25/shortcuts.xml
Labels: 🛬 needs landing

#5848 For #5847, #5824 Fix entries in the open in app list.
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5873 Telemetry migration: Remove obsolete telemetry
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: 🛬 needs landing

#5815 Update sumo url builder
  app/src/main/java/org/mozilla/focus/settings/privacy/studies/StudiesFragment.kt
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
Labels: 🛬 needs landing

#5872 For #4967: Remove wrapper for ads telemetry.
  app/src/main/java/org/mozilla/focus/telemetry/FactsProcessor.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: 🛬 needs landing

#5839 For #5547: Migrate app opened from external intents telemetry.
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryMiddleware.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: 🛬 needs landing

#5890 Close #5879: Add proguard rules for native components
  app/proguard-rules.pro
Labels: 🛬 needs landing

#5811 Add Completed section to Studies screen
  app/src/main/java/org/mozilla/focus/settings/privacy/studies/StudiesViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#5909 Issue #5908 - WebCompatReporterFeature - Use `focus-geckoview` as the productName.
  app/src/main/java/org/mozilla/focus/Components.kt
Labels: 🛬 needs landing

#5904 For #5902: Remove telemetry for app being in foreground or background.
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: 🛬 needs landing

#5888 No issue: Add missing PR numbers in metrics.yaml.
  app/metrics.yaml
Labels: 🛬 needs landing

#5906 For #5313: Re-enables enableSearchSuggestionOnFirstRunTest and adds new disableSearchSuggestionOnFirstRunTest
  app/src/androidTest/java/org/mozilla/focus/activity/SearchTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SearchRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsSearchMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#5869 For #5635: Migrate onboarding related telemetry.
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/fragment/FirstrunFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: 🛬 needs landing

#5911 For #5594: Also Stop GeckoSession when releasing acquired GeckoDisplay.
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5895 l10n-tests-add-screengrabfile
  Screengrabfile
Labels: 🛬 needs landing

#5800 Issue #5795: Replace "multiple tabs" feature flag with Nimbus experiment
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/contextmenu/ContextMenuCandidates.kt
  app/src/main/java/org/mozilla/focus/experiments/ExperimentalFeatures.kt
  app/src/main/java/org/mozilla/focus/experiments/ExperimentalTabsFeatures.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/tabs/MergeTabsMiddleware.kt
  app/src/main/java/org/mozilla/focus/utils/Features.kt
Labels: 🛬 needs landing

#5852 Relocate erase and tabs counter to toolbar
  app/build.gradle
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/EnhancedTrackingProtectionSettingsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/EraseBrowsingDataTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/FirstRunDialogueTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ImageSelectTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SearchTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/focus/privacy/LocalSessionStorageTest.kt
  app/src/androidTest/java/org/mozilla/focus/privacy/WebViewDataTest.java
  app/src/main/java/org/mozilla/focus/browser/binding/TabCountBinding.kt
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/browser/integration/FullScreenIntegration.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/session/ui/EraseViewHolder.kt
  app/src/main/java/org/mozilla/focus/session/ui/TabSheetFragment.kt
  app/src/main/java/org/mozilla/focus/session/ui/TabsAdapter.kt
  app/src/main/java/org/mozilla/focus/utils/FocusSnackbar.kt
  app/src/main/java/org/mozilla/focus/utils/FocusSnackbarDelegate.kt
  app/src/main/java/org/mozilla/focus/utils/ViewUtils.kt
  app/src/main/java/org/mozilla/focus/widget/FloatingActionButtonBehavior.kt
  app/src/main/java/org/mozilla/focus/widget/FloatingEraseButton.java
  app/src/main/java/org/mozilla/focus/widget/FloatingSessionsButton.java
  app/src/main/java/org/mozilla/focus/widget/ResizableKeyboardViewDelegate.java
  app/src/main/res/layout/fragment_browser.xml
  app/src/main/res/layout/fragment_sessionssheet.xml
  app/src/main/res/layout/item_erase.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegrationTest.kt
  app/src/test/java/org/mozilla/focus/browser/integration/FullScreenIntegrationTest.kt
Labels: 🛬 needs landing

#5886 For #5885: Migrate autocomplete domains related telemetry.
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteAddFragment.kt
  app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteListFragment.kt
  app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteRemoveFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: 🛬 needs landing

#5917 For #5914: Migrate telemetry related to back button navigation.
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
Labels: 🛬 needs landing

#5898 For #5897: Migrate report site issue telemetry.
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/telemetry/FactsProcessor.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
Labels: 🛬 needs landing

#5932 Use the correct value of toolbar height at dynamic behavior
  app/src/main/java/org/mozilla/focus/ext/BrowserToolbar.kt
Labels: 🛬 needs landing

#5941 Update remote debugging state
  app/src/main/java/org/mozilla/focus/engine/EngineSharedPreferencesListener.kt
  app/src/main/java/org/mozilla/focus/settings/AdvancedSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/settings/privacy/PrivacySecuritySettingsFragment.kt
Labels: 🛬 needs landing

#5827 Add callback to finish exceptions removal before navigation
  app/src/main/java/org/mozilla/focus/exceptions/ExceptionsListFragment.kt
  app/src/main/res/layout/fragment_exceptions_domains.xml
Labels: 🛬 needs landing
