Repository mozilla-mobile/focus-android, pull requests merged in 2021-10, with the labels that each got.

#5522 Update shortcut context menu background
  app/src/main/java/org/mozilla/focus/topsites/TopSites.kt
Labels: 🛬 needs landing

#5496 Add nightly support
  .cron.yml
  .taskcluster.yml
  taskcluster/ci/build/kind.yml
  taskcluster/ci/push-apk/kind.yml
  taskcluster/ci/signing/kind.yml
  taskcluster/focus_android_taskgraph/target_tasks.py
  taskcluster/focus_android_taskgraph/transforms/push_apk.py
Labels: 🛬 needs landing (squash)

#5507 Update floating button auto hide state in real time
  app/src/main/java/org/mozilla/focus/widget/FloatingActionButtonBehavior.java
  app/src/main/java/org/mozilla/focus/widget/FloatingEraseButton.java
  app/src/main/java/org/mozilla/focus/widget/FloatingSessionsButton.java
Labels: 🛬 needs landing

#5525 Add Release push apk support
  taskcluster/ci/build/kind.yml
  taskcluster/ci/push-apk/kind.yml
  taskcluster/ci/signing/kind.yml
  taskcluster/focus_android_taskgraph/target_tasks.py
Labels: 🛬 needs landing (squash)

#5535 No issue: update the UI SmokeTests list
  app/src/androidTest/java/org/mozilla/focus/activity/AddToHomescreenTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ImageSelectTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MozillaSupportPagesTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SearchTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsBlockToggleTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchContextTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ToggleBlockTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/URLExceptionTest.kt
Labels: eng:ui-test, 🛬 needs landing

#5515 For #5506: Make search suggestions hint scrollable.
  app/src/main/res/layout/fragment_search_suggestions.xml
Labels: 🛬 needs landing

#5537 Update version to 94.0
  app/build.gradle
Labels: 🛬 needs landing
