Repository mozilla-mobile/focus-android, pull requests merged in 2021-04, with the labels that each got.

#4777 Issue #4650: Update release icons.
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/icon_background.png
  app/src/main/res/mipmap-hdpi/icon_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/icon_background.png
  app/src/main/res/mipmap-xhdpi/icon_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/icon_background.png
  app/src/main/res/mipmap-xxhdpi/icon_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/icon_background.png
  app/src/main/res/mipmap-xxxhdpi/icon_foreground.png
Labels: 🛬 needs landing

#4779 Fix leaving blank Activity on back stack.
  app/src/main/java/org/mozilla/focus/activity/EraseAndOpenShortcutActivity.kt
Labels: 🛬 needs landing

#4786 Resolves #4785: Explicitly set extractNativeLibs=true in app manifest
  app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#4783 Closes #4761: Integrate feature-search component.
  app/build.gradle
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/activity/TextActionActivity.kt
  app/src/main/java/org/mozilla/focus/ext/AndroidViewModel.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/search/BingSearchEngineFilter.kt
  app/src/main/java/org/mozilla/focus/search/CustomSearchEngineProvider.kt
  app/src/main/java/org/mozilla/focus/search/CustomSearchEngineStore.kt
  app/src/main/java/org/mozilla/focus/search/HiddenSearchEngineFilter.kt
  app/src/main/java/org/mozilla/focus/search/ManualAddSearchEnginePreference.kt
  app/src/main/java/org/mozilla/focus/search/RadioSearchEngineListPreference.kt
  app/src/main/java/org/mozilla/focus/search/SearchEngineListPreference.kt
  app/src/main/java/org/mozilla/focus/search/SearchEnginePreference.kt
  app/src/main/java/org/mozilla/focus/search/SearchEngineWriter.kt
  app/src/main/java/org/mozilla/focus/search/SearchFilterMiddleware.kt
  app/src/main/java/org/mozilla/focus/search/SearchMigration.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsFetcher.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsPreferences.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/SearchSuggestionsViewModel.kt
  app/src/main/java/org/mozilla/focus/session/IntentProcessor.kt
  app/src/main/java/org/mozilla/focus/settings/InstalledSearchEnginesSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/settings/RemoveSearchEnginesSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetrySettingsProvider.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/utils/SearchUtils.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/java/org/mozilla/focus/utils/UrlUtils.java
  app/src/test/java/org/mozilla/focus/search/SearchEngineWriterTest.kt
Labels: 🛬 needs landing

#4789 MainActivityFirstrunTestRule: Skip first run screen.
  app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityTestRule.kt
  app/src/main/java/org/mozilla/focus/state/AppAction.kt
  app/src/main/java/org/mozilla/focus/state/AppReducer.kt
Labels: 🛬 needs landing

#4790 Replace JCenter with Maven Central.
  build.gradle
Labels: 🛬 needs landing

#4797 Fix and add UI tests in EraseBrowsingDataTest
  app/src/androidTest/java/org/mozilla/focus/activity/EraseAllUserDataTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/EraseBrowsingDataTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/NotificationRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#4799 Upgrade to Android Components 75.0.20210413143139
  app/src/main/java/org/mozilla/focus/Components.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#4806 Fixed and re-enabled UI test MultitaskingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/EspressoHelper.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityTestRule.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: eng:ui-test, 🕵️‍♀️ needs review, 🛬 needs landing

#4810 Issue #4746: Move CrashReporter initialization to Components class.
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/CrashReporterWrapper.kt
  app/src/main/java/org/mozilla/focus/widget/TelemetrySwitchPreference.kt
Labels: 🛬 needs landing

#4809 Remove unused Gradle plugins.
  app/build.gradle
  build.gradle
Labels: 🛬 needs landing

#4804 Issue #4791: Introduce separate build flavor for "Beta".
  app/build.gradle
  app/src/focusBeta/java/org/mozilla/focus/utils/AdjustHelper.java
  app/src/klarBeta/java/org/mozilla/focus/utils/AdjustHelper.java
  app/src/klarBeta/res/xml-v25/shortcuts.xml
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/utils/AppConstants.kt
Labels: 🛬 needs landing

#4812 Fixed and re-enabled ShareWebsiteTest.kt UI test
  app/src/androidTest/java/org/mozilla/focus/activity/ShareWebsiteTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/ThreeDotMainMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#4811 Close #4801: Vendor service-telemetry into Focus
  app/build.gradle
  build.gradle
  service-telemetry/.gitignore
  service-telemetry/README.md
  service-telemetry/build.gradle
  service-telemetry/proguard-rules.pro
  service-telemetry/src/main/AndroidManifest.xml
  service-telemetry/src/main/java/org/mozilla/telemetry/Telemetry.java
  service-telemetry/src/main/java/org/mozilla/telemetry/TelemetryHolder.java
  service-telemetry/src/main/java/org/mozilla/telemetry/config/TelemetryConfiguration.java
  service-telemetry/src/main/java/org/mozilla/telemetry/event/TelemetryEvent.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/ArchMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/ClientIdMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/CreatedDateMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/CreatedDateMeasurementNew.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/CreatedTimestampMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/CreatedTimestampMeasurementNew.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/DefaultSearchMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/DeviceMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/EventsMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/ExperimentsMapMeasurement.kt
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/ExperimentsMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/FirstRunProfileDateMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/LocaleMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/MetricsMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/OperatingSystemMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/OperatingSystemVersionMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/PocketIdMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/ProcessStartTimestampMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/SearchesMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/SequenceMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/SessionCountMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/SessionDurationMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/SettingsMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/StaticMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/TelemetryMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/TimezoneOffsetMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/measurement/VersionMeasurement.java
  service-telemetry/src/main/java/org/mozilla/telemetry/net/TelemetryClient.kt
  service-telemetry/src/main/java/org/mozilla/telemetry/ping/TelemetryCorePingBuilder.java
  service-telemetry/src/main/java/org/mozilla/telemetry/ping/TelemetryEventPingBuilder.java
  service-telemetry/src/main/java/org/mozilla/telemetry/ping/TelemetryMobileEventPingBuilder.java
  service-telemetry/src/main/java/org/mozilla/telemetry/ping/TelemetryMobileMetricsPingBuilder.java
  service-telemetry/src/main/java/org/mozilla/telemetry/ping/TelemetryPing.java
  service-telemetry/src/main/java/org/mozilla/telemetry/ping/TelemetryPingBuilder.java
  service-telemetry/src/main/java/org/mozilla/telemetry/ping/TelemetryPocketEventPingBuilder.java
  service-telemetry/src/main/java/org/mozilla/telemetry/schedule/TelemetryScheduler.java
  service-telemetry/src/main/java/org/mozilla/telemetry/schedule/jobscheduler/JobSchedulerTelemetryScheduler.java
  service-telemetry/src/main/java/org/mozilla/telemetry/schedule/jobscheduler/TelemetryJobService.java
  service-telemetry/src/main/java/org/mozilla/telemetry/serialize/JSONPingSerializer.java
  service-telemetry/src/main/java/org/mozilla/telemetry/serialize/TelemetryPingSerializer.java
  service-telemetry/src/main/java/org/mozilla/telemetry/storage/FileTelemetryStorage.java
  service-telemetry/src/main/java/org/mozilla/telemetry/storage/TelemetryStorage.java
  service-telemetry/src/main/java/org/mozilla/telemetry/util/ContextUtils.java
  service-telemetry/src/main/java/org/mozilla/telemetry/util/FileUtils.java
  service-telemetry/src/main/java/org/mozilla/telemetry/util/IOUtils.java
  service-telemetry/src/main/java/org/mozilla/telemetry/util/StringUtils.java
  settings.gradle
Labels: 🕵️‍♀️ needs review

#4813 Remove old survey code.
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#4814 Remove unused shavar blocklist
  .gitmodules
  app/build.gradle
  shavar-prod-lists/.travis.yml
  shavar-prod-lists/CODE_OF_CONDUCT.md
  shavar-prod-lists/LICENSE
  shavar-prod-lists/README.md
  shavar-prod-lists/adGuard-blacklist.json
  shavar-prod-lists/disconnect-blacklist.json
  shavar-prod-lists/disconnect-entitylist.json
  shavar-prod-lists/easyList-blacklist.json
  shavar-prod-lists/easyPrivacy-blacklist.json
  shavar-prod-lists/fanBoyAnnoyance-blacklist.json
  shavar-prod-lists/fanBoySocial-blacklist.json
  shavar-prod-lists/google_mapping.json
  shavar-prod-lists/scripts/json_verify.py
  shavar-prod-lists/social-tracking-protection-blacklist.json
  shavar-prod-lists/tests/disconnect_blacklist_invalid.json
  shavar-prod-lists/tests/disconnect_blacklist_valid.json
  shavar-prod-lists/tests/google_mapping_invalid.json
Labels: 🛬 needs landing

#4815 Bump version to 8.15.1.
  app/build.gradle
Labels: 🛬 needs landing

#4818 Update to Android Components 90.0
  app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteListFragment.kt
  app/src/main/java/org/mozilla/focus/exceptions/ExceptionsListFragment.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#4819 Re-enabled URLAutocompleteTest.kt UI tests
  app/src/androidTest/java/org/mozilla/focus/activity/SearchTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/URLAutocompleteTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SearchRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsSearchMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#4822 Fixed and re-enabled AddToHomescreenTest.kt UI tests
  app/src/androidTest/java/org/mozilla/focus/activity/AddToHomescreenTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/AddToHomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/ThreeDotMainMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#4827 Re-enable BadURLTest.kt UI tests. Renamed to ErrorPagesTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/BadURLTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ErrorPagesTest.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#4828 Fixed and re-enabled CustomTabTest.kt UI tests
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/CustomTabRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/HomeScreenRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#4833 Re-enabled AccessAboutAndYourRightsPagesTest.kt. Renamed it to MozillaSupportPagesTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/AccessAboutAndYourRightsPagesTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MozillaSupportPagesTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsMozillaMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/ThreeDotMainMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#4835 Fixes #4825: restore network connection after noNetworkConnectionErrorPageTest
  app/src/androidTest/java/org/mozilla/focus/activity/ErrorPagesTest.kt
Labels: eng:ui-test, 🛬 needs landing

#4829 Switch from master to main branch and remove unused code.
  .github/ISSUE_TEMPLATE/release_checklist_template.md
  .taskcluster.yml
  CONTRIBUTING.md
  README.md
  app/proguard-rules.pro
  app/src/main/java/org/mozilla/focus/web/Download.java
  app/src/main/java/org/mozilla/focus/web/HttpAuthenticationDialogBuilder.java
  app/src/main/java/org/mozilla/focus/web/IFindListener.java
  app/src/main/java/org/mozilla/focus/webview/ErrorPage.java
  app/src/main/java/org/mozilla/focus/webview/NestedWebView.java
  app/src/main/java/org/mozilla/focus/webview/TelemetryAutofillCallback.kt
  app/src/main/java/org/mozilla/focus/webview/matcher/BlocklistProcessor.java
  app/src/main/java/org/mozilla/focus/webview/matcher/EntityList.java
  app/src/main/java/org/mozilla/focus/webview/matcher/EntityListProcessor.java
  app/src/main/java/org/mozilla/focus/webview/matcher/Trie.java
  app/src/main/java/org/mozilla/focus/webview/matcher/UrlMatcher.java
  app/src/main/java/org/mozilla/focus/webview/matcher/util/FocusString.java
  app/src/main/res/raw/errorpage.html
  app/src/main/res/raw/errorpage_style.css
  app/src/main/res/raw/google_mapping.json
  app/src/test/java/org/mozilla/focus/web/DownloadTest.java
  tools/l10n/android2po/README.md
  tools/l10n/android2po/a2po.py
  tools/l10n/android2po/commands.py
  tools/l10n/android2po/config.py
  tools/l10n/android2po/convert.py
  tools/l10n/android2po/env.py
  tools/l10n/android2po/patch.py
  tools/l10n/android2po/program.py
  tools/l10n/android2po/requirements.txt
  tools/l10n/android2po/utils.py
  tools/l10n/check_locales.py
  tools/l10n/check_translations.py
  tools/l10n/create_commits.sh
  tools/l10n/export-strings.sh
  tools/l10n/fix_locale_folders.sh
  tools/l10n/import-strings.sh
  tools/taskcluster/android-wait-for-emulator.sh
  tools/taskcluster/create-pull-request.py
  tools/taskcluster/import_strings_and_create_pull_request.sh
  tools/taskcluster/lib/tasks.py
  tools/taskcluster/release.py
  tools/taskcluster/schedule-main-build.py
  tools/taskcluster/schedule-screenshots.py
  tools/taskcluster/screencap-server.py
  tools/taskcluster/take-screenshots.sh
Labels: 🛬 needs landing

#4830 Issue #4342: MainActivity: Use 'singleTask'.
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/focus/session/SessionNotificationService.kt
Labels: 🛬 needs landing

#4837 Issue #4820: generate_build_task(): Do not try to run removed check_translations.py
  tools/taskcluster/schedule-main-build.py
Labels: 🛬 needs landing

#4838 Issue #4781: Inject MLS token into BuildConfig.
  app/build.gradle
  tools/taskcluster/get-mls-token.py
  tools/taskcluster/release.py
Labels: 🛬 needs landing

#4840 For #4839: Disable noNetworkConnectionErrorPageTest causing failures …
  app/src/androidTest/java/org/mozilla/focus/activity/ErrorPagesTest.kt
Labels: eng:ui-test, 🛬 needs landing
