Repository mozilla-mobile/focus-android, pull requests merged in 2021-03, with the labels that each got.

#4709 Add configuration for enabling mergify
  .mergify.yml
Labels: 🕵️‍♀️ needs review

#4518 Closes #4517: Clear listOfTips before populate it
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
Labels: 🛬 needs landing

#4711 Update Kotlin and Coroutine version
  app/build.gradle
  app/src/main/java/org/mozilla/focus/utils/Debounce.kt
  build.gradle
Labels: 🛬 needs landing

#4712 BrowserFragment: Start to replace Session usage with browser-state
  app/src/main/java/org/mozilla/focus/browser/binding/MenuBinding.kt
  app/src/main/java/org/mozilla/focus/ext/SessionState.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/menu/browser/RequestDesktopCheckItemViewHolder.kt
Labels: 🛬 needs landing

#4715 Replace SessionManager usage with calling use cases.
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
  app/src/main/java/org/mozilla/focus/session/SessionNotificationService.kt
  app/src/main/java/org/mozilla/focus/session/ui/EraseViewHolder.kt
  app/src/main/java/org/mozilla/focus/settings/LearnMoreSwitchPreference.kt
  app/src/main/java/org/mozilla/focus/settings/MozillaSettingsFragment.kt
Labels: 🛬 needs landing

#4716 Replace NotificationSessionObserver with Middleware.
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/notification/PrivateNotificationMiddleware.kt
  app/src/main/java/org/mozilla/focus/session/NotificationSessionObserver.kt
  app/src/main/java/org/mozilla/focus/utils/TabUtils.kt
Labels: 🛬 needs landing

#4720 Replace TelemetrySessionObserver with Middleware.
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryMiddleware.kt
Labels: 🛬 needs landing

#4721 Replace more SessionManager usages with BrowserStore or use cases.
  app/src/main/java/org/mozilla/focus/activity/EraseAndOpenShortcutActivity.kt
  app/src/main/java/org/mozilla/focus/activity/EraseShortcutActivity.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/FirstrunFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
Labels: 🛬 needs landing

#4722 Migrate tab sheet to use BrowserStore instead of SessionManager.
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/session/ui/EraseViewHolder.kt
  app/src/main/java/org/mozilla/focus/session/ui/TabSheetFragment.kt
  app/src/main/java/org/mozilla/focus/session/ui/TabViewHolder.kt
  app/src/main/java/org/mozilla/focus/session/ui/TabsAdapter.kt
Labels: 🛬 needs landing

#4724 Update Robolectric to 4.4 and remove Jetifier
  app/build.gradle
  gradle.properties
Labels: 🛬 needs landing

#4719 Closed #4718: Re-add Google Cloud SDK to Dockerfile
  tools/docker/Dockerfile
Labels: 🛬 needs landing

#4725 Close #4723: Use CustomTabsService from Components
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/activity/CustomTabActivity.kt
  app/src/main/java/org/mozilla/focus/customtabs/CustomTabsService.java
  app/src/main/java/org/mozilla/focus/customtabs/CustomTabsService.kt
Labels: 🛬 needs landing

#4727 For issue #4540: Update tracking protection policy when cookie setting change
  app/src/main/java/org/mozilla/focus/engine/EngineSharedPreferencesListener.kt
Labels: 🛬 needs landing

#4750 Closes #4726: Use updated Docker image (1.6)
  .taskcluster.yml
  tools/taskcluster/lib/tasks.py
  tools/taskcluster/schedule-master-build.py
Labels: 🕵️‍♀️ needs review

#4754 Remove architecture product flavor and use APK split instead. And run…
  .taskcluster.yml
  README.md
  app/build.gradle
  app/src/main/java/org/mozilla/focus/utils/AppConstants.kt
  quality/pre-push-recommended.sh
  tools/docker/Dockerfile
  tools/taskcluster/execute-firebase-tests.sh
  tools/taskcluster/flank-conf-geckoview-arm.yml
  tools/taskcluster/flank-conf-webview-arm.yml
  tools/taskcluster/flank-conf-webview-x86.yml
  tools/taskcluster/flank.yml
  tools/taskcluster/google-firebase-testlab-login.sh
  tools/taskcluster/schedule-master-build.py
Labels: 🛬 needs landing

#4762 Convert UI tests from Java to Kotlin
  app/src/androidTest/java/org/mozilla/focus/activity/AccessAboutAndYourRightsPagesTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/AccessAboutAndYourRightsPagesTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/AddToHomescreenTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/AddToHomescreenTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/BadURLTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/BadURLTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ChangeSearchEngineTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/ChangeSearchEngineTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/EraseAllUserDataTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/EraseAllUserDataTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/FirstRunDialogueTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/FirstRunDialogueTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ImageSelectTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/ImageSelectTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/OpenInExternalBrowserDialogueTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/OpenInExternalBrowserDialogueTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsBlockToggleTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsBlockToggleTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ShareWebsiteTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/ShareWebsiteTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchContextTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchContextTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchLocaleTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchLocaleTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ToggleBlockTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/ToggleBlockTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/URLAutocompleteTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/URLAutocompleteTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/URLExceptionTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/URLExceptionTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/URLMismatchTest.java
  app/src/androidTest/java/org/mozilla/focus/activity/URLMismatchTest.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/EspressoHelper.java
  app/src/androidTest/java/org/mozilla/focus/helpers/EspressoHelper.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityFirstrunTestRule.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.java
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/FirstRunScreenshots.java
  app/src/androidTest/java/org/mozilla/focus/screenshots/ScreenshotTest.java
Labels: eng:ui-test, 🕵️‍♀️ needs review

#4770 Refactor UI test AddSettingsTest
  app/src/androidTest/java/org/mozilla/focus/activity/AccessSettingsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsAdvancedMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsGeneralMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsMozillaMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsPrivacyMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsSearchMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#4780 Move Android Components version to separate file for automation.
  app/build.gradle
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing
