Repository mozilla-mobile/focus-android, pull requests merged in 2021-09, with the labels that each got.

#5278 For #4929: Update whats new button icon color according to designs.
  app/src/main/res/drawable/ic_whats_new.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: 🛬 needs landing

#5300 Change taskcluster.yml file
  .taskcluster.yml
Labels: 🛬 needs landing

#5289 For #4993: Update floating erase button colors to match spec
  app/src/main/res/layout/fragment_browser.xml
Labels: 🛬 needs landing

#5296 Update the style of browser menu item
  app/src/main/java/org/mozilla/focus/menu/browser/CustomTabMenu.kt
  app/src/main/res/layout/request_desktop_check_menu_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: 🛬 needs landing

#5298 Tips carousel wasn't enabled/disabled properly
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/widget/ResizableKeyboardViewDelegate.java
Labels: 🛬 needs landing

#5281 Update tip number of lines and padding
  app/src/main/res/layout/tip_carousel_item.xml
Labels: 🛬 needs landing

#5220 Update toolbar background color
  app/src/focus/res/drawable/toolbar_url_background.xml
  app/src/klar/res/drawable/toolbar_url_background.xml
  app/src/main/java/org/mozilla/focus/theme/FocusTheme.kt
  app/src/main/res/layout/fragment_urlinput2.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: 🛬 needs landing

#5324 No issue: Update Android Components version.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5327 For #5056: Send shortcut count from storage not app state.
  app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt
Labels: 🛬 needs landing

#5326 Wrong text color for Powered by...
  app/src/main/java/org/mozilla/focus/menu/browser/CustomTabMenu.kt
Labels: 🛬 needs landing

#5332 For #5295: Improve checking for Fenix installed and default browser.
  app/src/main/java/org/mozilla/focus/telemetry/FenixProductDetector.kt
  app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt
Labels: 🛬 needs landing

#5342 For #5334: Add QueryAllPackagesPermission permission.
  app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#5321 #5319: Replace unicode with text for Android 5 & 6.
  app/src/main/java/org/mozilla/focus/fragment/AboutFragment.kt
Labels: 🛬 needs landing

#5341 For #5331: Pass string resource instead of text to Tips.
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
  app/src/main/java/org/mozilla/focus/tips/TipsAdapter.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#5352 For #5343: Update header and app name colors.
  app/src/main/res/layout/fragment_open_with.xml
  app/src/main/res/layout/item_app.xml
Labels: 🛬 needs landing

#5348 For #5343: Manually handle orientation changes in the app.
  app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#5320 For #5317: Check for engine name duplicates on validation.
  app/src/main/java/org/mozilla/focus/search/ManualAddSearchEnginePreference.kt
  app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt
Labels: 🛬 needs landing

#5315 For #5305: Allow menu to stretch up to 314dp width.
  app/src/main/res/values/dimens.xml
Labels: 🛬 needs landing

#5336 For #5333: Make ETP panel scrollable.
  app/src/main/res/layout/dialog_tracking_protection_sheet.xml
Labels: 🛬 needs landing

#5346 For #5128: Replace notification icon with new logo.
  app/src/main/res/drawable-hdpi/ic_notification.png
  app/src/main/res/drawable-xhdpi/ic_notification.png
  app/src/main/res/drawable-xxhdpi/ic_notification.png
  app/src/main/res/drawable-xxxhdpi/ic_notification.png
  app/src/main/res/drawable/ic_notification.xml
Labels: 🛬 needs landing

#5265 For #5257: Do not show add to home menu item if pinning is not supported
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/menu/browser/DefaultBrowserMenu.kt
Labels: 🛬 needs landing

#5329 Use separate application ID for Nightly builds
  app/build.gradle
Labels: 🛬 needs landing

#5330 Restore the position of find in page bar
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5359 For #937: fix file uploads
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5356 For #5318: Close response stream to allow another request.
  app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt
Labels: 🛬 needs landing

#5340 Change the color of navigation buttons and url background
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/browser/integration/NavigationButtonsIntegration.kt
  app/src/main/java/org/mozilla/focus/input/InputToolbarIntegration.kt
  app/src/main/res/drawable/toolbar_url_dark_background.xml
  app/src/main/res/drawable/toolbar_url_light_background.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: 🛬 needs landing

#5280 Add whats new url as a deeplink for the first tip
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
Labels: 🛬 needs landing

#5376 Add workaround to store TP exception on the TP panel
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5385 For #5375: Set private mode for toolbar explicitly.
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: 🛬 needs landing

#5406 For #4006: Restore last known state for tabs when one tab crashes.
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5405 For #5401: Update background drawable on orientation changed.
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: 🛬 needs landing

#5400 For #5397: Align preference header text to view start.
  app/src/main/res/layout/preference_section_header_layout.xml
Labels: 🛬 needs landing

#5393 For #5390: Use translated string for about fragment title.
  app/src/main/java/org/mozilla/focus/fragment/AboutFragment.kt
Labels: 🛬 needs landing

#5408 For #5383: Reload current tab on updating TrackingProtectionPolicy.
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5378 For fenix#21126: process performancetest intent if AC too.
  app/src/main/java/org/mozilla/focus/perf/Performance.kt
Labels: 🛬 needs landing

#5386 Increase the number of lines for a home tip
  app/src/main/res/layout/tip_carousel_item.xml
Labels: 🛬 needs landing

#5402 For #5369 show the broken lock icon when visiting a HTTP site
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/popup/PopupUtils.kt
  app/src/main/res/drawable/mozac_ic_broken_lock.xml
  app/src/main/res/layout/security_popup.xml
  app/src/test/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegrationTest.kt
Labels: 🛬 needs landing

#5415 Fix CustomTabTest.testCustomTabUI
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: 🛬 needs landing

#5418 For #5416: Remove tabs from general preferences description.
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/settings.xml
Labels: 🛬 needs landing

#5421 Override the ripple color used for "open in" items
  app/src/main/res/drawable/background_open_in_item.xml
  app/src/main/res/layout/item_app.xml
Labels: 🛬 needs landing

#5363 Migrate HomeMenu to use BrowserMenuItem
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/menu/home/HomeMenu.kt
  app/src/main/java/org/mozilla/focus/menu/home/HomeMenuAdapter.kt
  app/src/main/java/org/mozilla/focus/menu/home/HomeMenuItem.kt
  app/src/main/res/layout/fragment_urlinput2.xml
  app/src/main/res/layout/menu.xml
Labels: 🛬 needs landing

#5409 For #5307: Handle opening browser from external search intent.
  app/src/main/java/org/mozilla/focus/activity/TextActionActivity.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/state/AppReducer.kt
Labels: 🛬 needs landing

#5414 Update production launch icons
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: 🛬 needs landing

#5423 Redundant onDraw calls on FloatingSessionsButton
  app/src/main/java/org/mozilla/focus/widget/FloatingSessionsButton.java
Labels: 🛬 needs landing

#5411 Remove ResizableLayout from the main page
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/tips/TipsHorizontalCarousel.kt
  app/src/main/java/org/mozilla/focus/widget/ResizableKeyboardViewDelegate.java
  app/src/main/res/layout/fragment_urlinput.xml
Labels: 🛬 needs landing

#5425 For #5424: Show browser toolbar when navigating to another page.
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/test/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegrationTest.kt
Labels: 🛬 needs landing

#5420 For #5257: Use activity alias for launcher activity.
  app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#5145 Add taskgraph
  .taskcluster.yml
  app/build.gradle
  automation/taskcluster/androidTest/flank-x86.yml
  automation/taskcluster/androidTest/parse-ui-test.py
  automation/taskcluster/androidTest/ui-test.sh
  build.gradle
  buildSrc/src/main/java/org/mozilla/focus/gradle/tasks/GithubDetailsTask.kt
  taskcluster/ci/build/kind.yml
  taskcluster/ci/config.yml
  taskcluster/ci/docker-image/kind.yml
  taskcluster/ci/fetch/kind.yml
  taskcluster/ci/lint/kind.yml
  taskcluster/ci/test/kind.yml
  taskcluster/ci/toolchain/android.yml
  taskcluster/ci/toolchain/kind.yml
  taskcluster/ci/ui-test/kind.yml
  taskcluster/docker/android-build/Dockerfile
  taskcluster/docker/base/Dockerfile
  taskcluster/docker/ui-tests/Dockerfile
  taskcluster/focus_android_taskgraph/__init__.py
  taskcluster/focus_android_taskgraph/gradle.py
  taskcluster/focus_android_taskgraph/job.py
  taskcluster/focus_android_taskgraph/loader/__init__.py
  taskcluster/focus_android_taskgraph/loader/multi_dep.py
  taskcluster/focus_android_taskgraph/routes.py
  taskcluster/focus_android_taskgraph/target_tasks.py
  taskcluster/focus_android_taskgraph/transforms/build.py
  taskcluster/focus_android_taskgraph/transforms/multi_dep.py
  taskcluster/focus_android_taskgraph/transforms/test.py
  taskcluster/focus_android_taskgraph/util.py
  taskcluster/focus_android_taskgraph/worker_types.py
  taskcluster/scripts/decision-install-sdk.sh
  taskcluster/scripts/get-secret.py
  taskcluster/scripts/toolchain/android-gradle-dependencies.sh
  taskcluster/scripts/toolchain/android-gradle-dependencies/after.sh
  taskcluster/scripts/toolchain/android-gradle-dependencies/before.sh
  taskcluster/scripts/toolchain/android-gradle-dependencies/nexus.xml
  taskcluster/scripts/toolchain/repack-android-sdk-linux.sh
  taskcluster/scripts/write-dummy-secret.py
Labels: eng:automation, 🛬 needs landing (squash)

#5428 Update Mergify rules to verify status of taskhgraph tasks.
  .mergify.yml
Labels: 🕵️‍♀️ needs review

#5434 For #5429: Remove initial workaround for opening search from another app
  app/src/main/java/org/mozilla/focus/state/AppReducer.kt
Labels: 🛬 needs landing

#5436 No issue: Fix FTL shard timeouts
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SearchRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/BrowserScreenScreenshots.java
Labels: needs merge, eng:ui-test, 🛬 needs landing

#5439 For #5438 - Fix verifyPageSecurityIconAndInfo
  app/src/androidTest/java/org/mozilla/focus/activity/SafeBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#5437 Fix .taskcluster.yml rendering to avoid error when no tasks are produced
  .taskcluster.yml
Labels: 🛬 needs landing

#5468 Update Android Components version
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5462 Change google play store channel
  .taskcluster.yml
  tools/taskcluster/release.py
Labels: 🛬 needs landing

#5472 Update keepHidden default value
  app/src/main/java/org/mozilla/focus/widget/FloatingEraseButton.java
Labels: 🛬 needs landing

#5479 Replace ContextCompat with AppCompatResources
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
Labels: 🛬 needs landing

#5453 Update logo height
  app/src/main/res/layout/fragment_urlinput.xml
Labels: 🛬 needs landing

#5489 Issue #5486: Update EngineView height on fullscreen updates
  app/src/main/java/org/mozilla/focus/browser/integration/FullScreenIntegration.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#5485 Close #5484: Do not show url background in a Custom Tab
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
Labels: 🛬 needs landing

#5483 Remove debug key for signing nightly.
  app/build.gradle
Labels: 🛬 needs landing

#5480 Add about:crashes support
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/focus/activity/CrashListActivity.kt
  app/src/main/java/org/mozilla/focus/engine/AppContentInterceptor.kt
Labels: 🛬 needs landing

#5459 Update the size of pro tip dots and y position
  app/src/main/java/org/mozilla/focus/tips/DotPagerIndicatorDecoration.kt
  app/src/main/res/layout/tip_carousel_item.xml
Labels: 🛬 needs landing

#5458 Pro tip touch area increase
  app/src/main/java/org/mozilla/focus/tips/TipsAdapter.kt
Labels: 🛬 needs landing

#5491 Revert 5472 pr
  app/src/main/java/org/mozilla/focus/widget/FloatingEraseButton.java
Labels: 🛬 needs landing

#5497 No issue: Update Android Components version to 93.0.11
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5499 possibly fix taskgraph release
  .taskcluster.yml
Labels: 🛬 needs landing

#5502 Update Android Components version to 94.0.20210928190108
  app/build.gradle
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#5503 Update dev launcher icon
  app/src/debug/res/drawable/icon_background.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/debug/res/mipmap-hdpi/ic_launcher.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-hdpi/icon_foreground.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xhdpi/icon_foreground.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxhdpi/icon_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/icon_foreground.png
Labels: 🛬 needs landing

#5505 Issue #5474: Ship all locales and disable filtering
  tools/l10n/filter-release-translations.py
  tools/l10n/locales.py
Labels: 🛬 needs landing

#5510 Issue #5508: Add legacy ic_launcher icons for release
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: 🛬 needs landing

#5516 Revert using activity-alias for launcher activity.
  app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#5511 Issue #5508: Update Nightly variant icon resource references
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/nightly/res/drawable-v24/icon_foreground.xml
  app/src/nightly/res/drawable/ic_launcher_background.xml
  app/src/nightly/res/drawable/ic_launcher_foreground.xml
  app/src/nightly/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/nightly/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: 🛬 needs landing
