Repository mozilla-mobile/focus-android, pull requests merged in 2022-11, with the labels that each got.

#7953 No issue: Simplify openCustomTabInFocusTest.
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
Labels: 🛬 needs landing

#7956 Update fastlane screengrab to 2.1.1
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#7958 Update to Android-Components 108.0.20221101143225
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#7964 For #7963 - Add a Focus prefix to GitHub actions
  .github/workflows/focus-sync-strings.yml
  .github/workflows/focus-update-ac.yml
Labels: 🛬 needs landing

#7916 For #7915: Upgrade Compose to 1.3.0.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#7976 For #7975 - Fix A-C auto publish docs in README.md
  README.md
Labels: 🛬 needs landing

#7978 For #7967: Check if button was either pressed or a11y focused.
  app/src/main/java/org/mozilla/focus/search/RadioSearchEngineListPreference.kt
Labels: 🛬 needs landing

#7971 For #7970 - added search metrics to baseline ping
  app/metrics.yaml
Labels: 🛬 needs landing, eng:reopen-for-qa

#7968 No issue: Refactor web page items clicks and setting text
  app/src/androidTest/java/org/mozilla/focus/activity/WebControlsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#7988 For #7695 re-enable trashButtonTest UI test
  app/src/androidTest/java/org/mozilla/focus/activity/EraseBrowsingDataTest.kt
Labels: eng:ui-test, 🛬 needs landing

#7977 For #7966: Update buttons text for add to home dialog.
  app/src/main/res/layout/dialog_add_to_homescreen2.xml
Labels: 🛬 needs landing

#7998 For #7887 fix flaky verifyDownloadedFileOnStorageTest UI test
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#8007 For #8006: Disable recent screen OS screenshot.
  app/src/main/java/org/mozilla/focus/ext/Activity.kt
Labels: 🛬 needs landing

#7884 Update AndroidX testing libraries to the latest releases
  app/build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#8018 For #7927 - The homeScreen should not be displayed before the onBoarding
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/test/java/org/mozilla/focus/searchwidget/ExternalIntentNavigationTest.kt
Labels: 🛬 needs landing

#8010 For #6531 new clearSearchButtonTest UI smoke test
  app/src/androidTest/java/org/mozilla/focus/activity/SearchTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SearchRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#8025 Update version.txt to 109.0b1.
  version.txt
Labels: 🛬 needs landing

#8026 Update various AndroidX libraries to the latest releases
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#8011 Bug 1799967 - Migrate focus-android from AWS to GCP
  .taskcluster.yml
  taskcluster/ci/config.yml
Labels: eng:automation, 🛬 needs landing

#8033 Update AndroidX AppCompat to version 1.5.1
  buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#8032 Issue #8031: Fix wrong app name for Firefox Klar shortcut
  app/src/klar/res/values/app.xml
Labels: 🛬 needs landing

#8028 Remove all strings marked with moz:removedIn <= 106
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#8045 For #8042 - Enable New Onboarding Flow by default
  nimbus.fml.yaml
Labels: 🛬 needs landing

#8034 Update Material Components to version 1.7.0
  buildSrc/src/main/java/FocusDependencies.kt
Labels: 🛬 needs landing

#8055 For #8054 - Focus should not crash when search engines are restored.
  app/src/main/java/org/mozilla/focus/search/RadioSearchEngineListPreference.kt
Labels: 🛬 needs landing

#8051 Add initial_experiments.json Github Action
  .github/workflows/focus-update-nimbus-experiments.yml
Labels: 🛬 needs landing, 🛬 needs landing (squash)

#8068 Remove temoporary SDK 33 compat extension methods.
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsMozillaMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
  app/src/main/java/org/mozilla/focus/activity/InstallFirefoxActivity.kt
  app/src/main/java/org/mozilla/focus/browser/LocalizedContent.kt
  app/src/main/java/org/mozilla/focus/ext/Bundle.kt
  app/src/main/java/org/mozilla/focus/ext/Context.kt
  app/src/main/java/org/mozilla/focus/ext/Intent.kt
  app/src/main/java/org/mozilla/focus/ext/PackageManager.kt
  app/src/main/java/org/mozilla/focus/ext/Service.kt
  app/src/main/java/org/mozilla/focus/fragment/about/AboutFragment.kt
  app/src/main/java/org/mozilla/focus/search/ManualAddSearchEnginePreference.kt
  app/src/main/java/org/mozilla/focus/session/SessionNotificationService.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/SitePermissionOptionsFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/FenixProductDetector.kt
  app/src/main/java/org/mozilla/focus/utils/IntentUtils.kt
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
  app/src/test/java/org/mozilla/focus/utils/SupportUtilsTest.kt
Labels: 🛬 needs landing

#8072 Adopt NimbusBuilder from Android Components/AppServices
  app/src/main/java/org/mozilla/focus/experiments/NimbusSetup.kt
Labels: 🛬 needs landing (squash)

#8074 Replace using a boolean in config with GV's HardwareUtils isTablet.
  app/src/main/java/org/mozilla/focus/ext/Context.kt
  app/src/main/java/org/mozilla/focus/open/OpenWithFragment.java
  app/src/main/res/values-sw600dp/configuration.xml
  app/src/main/res/values/configuration.xml
Labels: 🛬 needs landing

#8076 For #7840: Add post notifications permission.
  app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#8089 For #1802596 Deleted XML entities in localized strings.
  app/build.gradle
  app/src/focusBeta/res/values/app.xml
  app/src/focusNightly/res/values/app.xml
  app/src/klar/res/values/app.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing
