Repository mozilla-mobile/focus-android, pull requests merged in 2022-09, with the labels that each got.

#7611 Add tabId for download feature
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#7615 For #7467: Update ktlint to 0.47.0.
  .editorconfig
  app/src/androidTest/java/org/mozilla/focus/activity/robots/ThreeDotMainMenuRobot.kt
  app/src/main/java/org/mozilla/focus/activity/CustomTabActivity.kt
  app/src/main/java/org/mozilla/focus/activity/InstallFirefoxActivity.kt
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/appreview/AppReviewStep.kt
  app/src/main/java/org/mozilla/focus/engine/EngineSharedPreferencesListener.kt
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingStep.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchOverlay.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/SitePermission.kt
  app/src/main/java/org/mozilla/focus/settings/privacy/PrivacySecuritySettingsFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/StartupPathProvider.kt
  app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/StartupStateProvider.kt
  app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/StartupTypeTelemetry.kt
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
  build.gradle
Labels: 🛬 needs landing

#7578 Merge top site tab
  app/src/main/java/org/mozilla/focus/topsites/TopSitesOverlay.kt
Labels: 🛬 needs landing

#7623 Remove multi-tabs experiment
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/contextmenu/ContextMenuCandidates.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/tabs/MergeTabsMiddleware.kt
  nimbus.fml.yaml
Labels: 🛬 needs landing

#7609 Update onboarding close button
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingFirstScreenCompose.kt
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingSecondScreenCompose.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusColors.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusTheme.kt
  app/src/main/res/drawable-hdpi/ic_onboarding_close.png
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#7515 Update tcp cfr string
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#7612 For #7610: Upgrade kotlin to 1.7.10 and compose compiler to 1.3.0.
  app/build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#7513 Don't clear search url before erase
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#7632 Bug 1781051 - simplify setting ownerEmail in .taskcluster.yml
  .taskcluster.yml
Labels: 🛬 needs landing

#7660 For #7659: Disable SettingsAdvancedTest#openLinksInAppsTest.
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsAdvancedTest.kt
Labels: eng:ui-test

#7671 Disable allowSocialTrackersTest and emailLinkTest UI tests
  app/src/androidTest/java/org/mozilla/focus/activity/EnhancedTrackingProtectionSettingsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/WebControlsTest.kt
Labels: eng:ui-test, 🛬 needs landing

#7684 Update version.txt to 107.0b1
  version.txt
Labels: 🛬 needs landing

#7648 For #7647: Upgrade core splash screen to stable version.
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#7696 For #5547: Add correct description for app opened metrics.
  app/metrics.yaml
Labels: 🛬 needs landing

#7421 Don't run nightly/beta UI tests on all pushes to the repo
  taskcluster/ci/build/kind.yml
  taskcluster/ci/ui-test/kind.yml
Labels: 🛬 needs landing

#7694 For #7693 Fix strings and comments for Onboarding Screens
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingSecondScreenCompose.kt
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#7691 For #7690: Upgrade Gradle plugin and wrapper.
  buildSrc/src/main/java/Dependencies.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: 🛬 needs landing

#7713 For #7712: Treat ComposeViews as single unit in transitions.
  app/src/main/java/org/mozilla/focus/biometrics/BiometricAuthenticationFragment.kt
  app/src/main/java/org/mozilla/focus/compose/CFRPopup.kt
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingFirstFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingSecondFragment.kt
  app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetUtils.kt
  app/src/main/java/org/mozilla/focus/settings/BaseComposeFragment.kt
Labels: 🛬 needs landing

#7719 For #7511 - Custom set to default onboarding page for Huawei users
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingController.kt
  app/src/main/java/org/mozilla/focus/utils/ManufacturerCodes.kt
Labels: 🛬 needs landing

#7703 Bug 1789398 - ensure task["metadata"]["owner"] is not empty on github…
  .taskcluster.yml
Labels: 🛬 needs landing

#7721 For #6531 new onboarding UI smoke test
  app/src/androidTest/java/org/mozilla/focus/activity/FirstRunTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/HomeScreenRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#7757 Fix long pressing links in UI tests
  app/src/androidTest/java/org/mozilla/focus/activity/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#7749 Fix flaky web controls UI tests
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#7760 No issue: Clean up SessionLoadedIdlingResource inits
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/CustomTabRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SearchRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsMozillaMenuRobot.kt
Labels: 🛬 needs landing

#7766 For #6531 new shortcutsDoNotOpenInNewTabTest UI smoke test
  app/src/androidTest/java/org/mozilla/focus/activity/ShortcutsTest.kt
Labels: eng:ui-test, 🛬 needs landing

#7722 For #7704 - If the phone hasn't voice search the microphone shouldn't appear
  app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetProvider.kt
  app/src/test/java/org/mozilla/focus/searchwidget/SearchWidgetProviderTest.kt
Labels: 🛬 needs landing

#7765 For #7764 - Make onBoarding feature changeable from Ui tests
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
Labels: 🛬 needs landing

#7768 For #7741 #7740 and #7668 fix flaky UI tests
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#7715 For #7712: Upgrade androidX transition to fix ComposeView transition crash
  app/build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing
