Repository mozilla-mobile/focus-android, pull requests merged in 2022-04, with the labels that each got.

#6782 For #6531: Improve coverage of erase data UI tests
  app/src/androidTest/assets/storage_start.html
  app/src/androidTest/java/org/mozilla/focus/activity/EraseBrowsingDataTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestAssetHelper.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/focus/privacy/LocalSessionStorageTest.kt
  app/src/androidTest/java/org/mozilla/focus/privacy/WebViewDataTest.java
Labels: eng:ui-test, 🛬 needs landing

#6814 For #5283: Re-enables openCustomTabInFocusTest and ads customTabNavigationButtonsTest
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/CustomTabRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/ThreeDotMainMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#6813 For #6708 & #6709: re-enable testVisitingMultipleSites, closeTabButtonTest UI tests
  app/src/androidTest/assets/genericPage.html
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/EnhancedTrackingProtectionSettingsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/OpenInExternalBrowserDialogueTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ShortcutsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchContextTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/TabsTrayRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestAssetHelper.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/NotificationScreenshots.java
Labels: eng:ui-test, 🛬 needs landing

#6822 Close PiP when the video is not in fullscreen anymore
  app/src/main/java/org/mozilla/focus/browser/integration/FullScreenIntegration.kt
Labels: 🛬 needs landing

#6823 [UI smoke test] For #6531: Adds share link UI test
  app/src/androidTest/java/org/mozilla/focus/activity/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#6829 Bump version to 101
  app/build.gradle
  version.txt
Labels: 🛬 needs landing (squash)

#6830 Update to Android-Components 100.0.0.
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#6785 Update text alignment of onboarding features
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingFragment.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusDimensions.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusTheme.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusTypography.kt
Labels: 🛬 needs landing

#6751 Remove navigation actions from custom tab
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
Labels: 🛬 needs landing

#6754 For #6504 SitePermissionScreen and SitePermissionOptionsScreen
  app/build.gradle
  app/src/androidTest/java/org/mozilla/focus/activity/AddToHomescreenTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/EnhancedTrackingProtectionSettingsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/EraseBrowsingDataTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SafeBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SearchTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsGeneralTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchContextTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/URLAutocompleteTest.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/HomeScreenScreenshots.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
  app/src/main/java/org/mozilla/focus/navigation/Navigator.kt
  app/src/main/java/org/mozilla/focus/settings/BaseComposeFragment.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/AutoplayFragment.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/AutoplayOption.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/SitePermissionOption.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/SitePermissionsFragment.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/DefaultSitePermissionOptionsScreenInteractor.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/HardwarePermissionCheckFeature.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/SitePermission.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/SitePermissionOptionListItem.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/SitePermissionOptionsFragment.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/SitePermissionOptionsFragmentCompose.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/SitePermissionOptionsScreenStore.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/SitePermissionOptionsStorage.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/SitePermissionOptionsStorageMiddleware.kt
  app/src/main/java/org/mozilla/focus/state/AppAction.kt
  app/src/main/java/org/mozilla/focus/state/AppReducer.kt
  app/src/main/java/org/mozilla/focus/state/AppState.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusColors.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusTheme.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/drawable/ic_autoplay_enabled.xml
  app/src/main/res/drawable/ic_camera_enabled.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/site_permissions.xml
  app/src/main/res/xml/site_permissions_autoplay.xml
Labels: 🛬 needs landing

#6657 Restore ui-test-x86-debug queue rule in mergify
  .mergify.yml
Labels: 🛬 needs landing (squash)

#6844 For #6835 disable failing verifyPrivacySettingsMenuTest UI test
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsTest.kt
Labels: eng:ui-test, 🛬 needs landing

#6853 For #6166 Fingerprint protects all the screens
  app/src/main/java/org/mozilla/focus/biometrics/LockObserver.kt
Labels: 🛬 needs landing

#6863 Add content description for SwitchWithDescription
  app/src/main/java/org/mozilla/focus/settings/privacy/TrackingProtectionPanel.kt
  app/src/main/java/org/mozilla/focus/widget/SwitchWithDescription.kt
Labels: 🛬 needs landing

#6869 Strings SitePermissions comment modification
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#6870 Update to JNA 5.8.0
  build.gradle
Labels: 🛬 needs landing

#6897 For #6894: Record exposure event for multi tabs experiment manually.
  app/src/main/java/org/mozilla/focus/contextmenu/ContextMenuCandidates.kt
  app/src/main/java/org/mozilla/focus/ext/Nimbus.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/tabs/MergeTabsMiddleware.kt
Labels: 🛬 needs landing

#6768 Exit PiP when launched externally with Intents
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
Labels: 🛬 needs landing

#6902 Dismiss tabs popup when the external container is clicked
  app/src/main/java/org/mozilla/focus/session/ui/TabsPopup.kt
Labels: 🛬 needs landing

#6873 for #6166 Fingerprint auth protects the home screen (shortcuts)
  app/src/main/java/org/mozilla/focus/biometrics/BiometricAuthenticationDialogFragment.kt
  app/src/main/java/org/mozilla/focus/biometrics/LockObserver.kt
  app/src/main/java/org/mozilla/focus/state/AppAction.kt
  app/src/main/java/org/mozilla/focus/state/AppReducer.kt
  app/src/main/java/org/mozilla/focus/topsites/TopSitesIntegration.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#6930 for #6928 Use a feature flag for fingerprint auth changes that that protect home screen
  app/src/main/java/org/mozilla/focus/biometrics/BiometricAuthenticationDialogFragment.kt
  app/src/main/java/org/mozilla/focus/utils/Features.kt
Labels: 🛬 needs landing
