Repository mozilla-mobile/focus-android, pull requests merged in 2022-08, with the labels that each got.

#7428 For #7423: Replace icon for navigate up/back button.
  app/src/main/java/org/mozilla/focus/compose/Modifier.kt
  app/src/main/java/org/mozilla/focus/settings/BaseComposeFragment.kt
Labels: 🛬 needs landing

#7464 Show all supported languages
  app/src/main/java/org/mozilla/focus/locale/screen/LanguageStorage.kt
  app/src/main/java/org/mozilla/focus/locale/screen/LocaleDescriptor.kt
Labels: 🛬 needs landing

#7418 Renew telemetry expiring in 106
  app/metrics.yaml
Labels: 🛬 needs landing

#7475 For #7318 fix flaky openLinksInAppsTest UI test
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsAdvancedTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#7474 For #7249 Create a search widget
  app/metrics.yaml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/focus/activity/IntentReceiverActivity.kt
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/searchwidget/SearchWidgetProvider.kt
  app/src/main/java/org/mozilla/focus/searchwidget/VoiceSearchActivity.kt
  app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/drawable-hdpi/focus_search_widget.png
  app/src/main/res/drawable-night-hdpi/focus_search_widget.png
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/search_widget_info.xml
  app/src/test/java/org/mozilla/focus/searchwidget/SearchWidgetProviderTest.kt
Labels: 🛬 needs landing

#7479 Update engine theme
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/settings/GeneralSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#7533 Set version to 106.0
  app/build.gradle
Labels: 🛬 needs landing

#7424 Don't run ui-test-x86-{nightly,beta} tasks on pull requests
  taskcluster/ci/ui-test/kind.yml
Labels: 🛬 needs landing

#7534 For #6296 - Remove Homepage Tips (Pro Tips) from Homepage
  app/metrics.yaml
  app/src/androidTest/java/org/mozilla/focus/activity/FirstRunTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MozillaSupportPagesTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/HomeScreenRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsMozillaMenuRobot.kt
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/settings/MozillaSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryWrapper.kt
  app/src/main/java/org/mozilla/focus/tips/DotPagerIndicatorDecoration.kt
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
  app/src/main/java/org/mozilla/focus/tips/TipsAdapter.kt
  app/src/main/java/org/mozilla/focus/tips/TipsHorizontalCarousel.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/layout/fragment_urlinput.xml
  app/src/main/res/layout/tip_carousel_item.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/mozilla_settings.xml
Labels: 🛬 needs landing

#7520 add about block to nimbus.fml.yaml
  nimbus.fml.yaml
Labels: 🛬 needs landing

#7538 For DENG-245: Add engine name to searchCount.
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: 🛬 needs landing

#7541 Add skr locale name
  app/src/main/java/org/mozilla/focus/locale/screen/LocaleDescriptor.kt
Labels: 🛬 needs landing

#7548 Add custom url without altering the text
  app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteAddFragment.kt
Labels: 🛬 needs landing

#7542 chore: Bump taskgraph to v3.0.0
  .taskcluster.yml
  taskcluster/focus_android_taskgraph/transforms/release_deps.py
  taskcluster/requirements.txt
Labels: 🛬 needs landing

#7568 update bot name
  taskcluster/ci/version-bump/kind.yml
Labels: 🛬 needs landing (squash)

#7572 Add transition animation for theme switching
  app/src/main/res/anim/fade_in.xml
  app/src/main/res/anim/fade_out.xml
  app/src/main/res/values/styles.xml
Labels: 🛬 needs landing
