Repository mozilla-mobile/focus-android, pull requests merged in 2022-06, with the labels that each got.

#7145 For #6908: Fix onboarding UI change and re-enable UI tests
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsPrivacyMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#7153 Update version to 103.0 in version.txt
  version.txt
Labels: 🛬 needs landing

#7157 Fix version format from version.txt
  version.txt
Labels: 🛬 needs landing

#7154 For #7113 and #6733 re-enabled SafeBrowsing and badURLCheckTest UI tests
  app/src/androidTest/java/org/mozilla/focus/activity/ErrorPagesTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SafeBrowsingTest.kt
Labels: eng:ui-test, 🛬 needs landing

#7156 Run CI for https://github.com/mozilla-mobile/focus-android/pull/7142
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
Labels: 🛬 needs landing

#7054 for #7053 Fix focus memory leak
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
Labels: 🛬 needs landing

#7155 Install splash screen in CrashListActivity.kt
  app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#7168 For #5807: replaces Espresso selectors in security info sheet
  app/src/androidTest/java/org/mozilla/focus/activity/SafeBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SiteSecurityInfoSheetRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#7199 No issue: Replace Java utils with Kotlin extensions.
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/ext/Context.kt
  app/src/main/java/org/mozilla/focus/search/MultiselectSearchEngineListPreference.kt
  app/src/main/java/org/mozilla/focus/utils/ContextUtils.kt
  app/src/main/java/org/mozilla/focus/utils/HardwareUtils.java
  app/src/main/java/org/mozilla/focus/utils/ViewUtils.kt
  app/src/main/java/org/mozilla/focus/widget/DefaultBrowserPreference.kt
Labels: 🛬 needs landing

#7124 Uplift translations from main to release branches
  .github/workflows/sync-strings.yml
Labels: 🛬 needs landing

#7238 For #6486, #6678: re-enable browsing notification tests
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchContextTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/NotificationRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#7235 Update to a version which support smaller naming scheme
  .github/workflows/sync-strings.yml
Labels: 🛬 needs landing

#7186 For #7079 Collect telemetry on how Focus was started and n which state it way
  app/build.gradle
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/activity/CustomTabActivity.kt
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/AppStartReasonProvider.kt
  app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/DefaultActivityLifecycleCallbacks.kt
  app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/StartupActivityLog.kt
  app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/StartupPathProvider.kt
  app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/StartupStateProvider.kt
  app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/StartupTypeTelemetry.kt
  app/src/test/java/org/mozilla/focus/telemetry/StartupActivityLogTest.kt
  app/src/test/java/org/mozilla/focus/telemetry/StartupPathProviderTest.kt
  app/src/test/java/org/mozilla/focus/telemetry/StartupStateProviderTest.kt
  app/src/test/java/org/mozilla/focus/telemetry/StartupTypeTelemetryTest.kt
  app/tags.yaml
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#7217 Remove unused strings
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#7229 For #7136 Don’t show shield icon CFR for pages with 0 trackers
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/cfr/CfrMiddleware.kt
  app/src/main/java/org/mozilla/focus/state/AppAction.kt
  app/src/main/java/org/mozilla/focus/state/AppReducer.kt
  app/src/main/java/org/mozilla/focus/state/AppState.kt
  app/src/test/java/org/mozilla/focus/cfr/CfrMiddlewareTest.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#7228 Stop triggering multiple nightlies off the same revision
  .taskcluster.yml
  taskcluster/focus_android_taskgraph/target_tasks.py
  taskcluster/requirements.in
Labels: 🛬 needs landing

#7263 Revert DDG exception added for search terms
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/utils/Features.kt
Labels: 🛬 needs landing

#7265 Update experiments timespan lifetime
  app/metrics.yaml
Labels: 🛬 needs landing

#7264 For #7257 Mixed match for has_content_blocked metric
  app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
Labels: 🛬 needs landing

#7266 Onboarding experiment is not applied from the first run
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/experiments/NimbusSetup.kt
Labels: 🛬 needs landing

#7288 Update version name to 104.0
  app/build.gradle
  version.txt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#7283 For #6060: re-enables UI test englishSystemLocaleTest()
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsGeneralTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsGeneralMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/StringsHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#7251 For #7236 Add metrics tags for all issues labels
  tools/update-glean-tags.py
Labels: 🛬 needs landing

#7276 For #7275: Build with SDK for Android 12 / API 32
  app/build.gradle
  service-telemetry/build.gradle
Labels: 🛬 needs landing

#7298 Refactor changeLocale method
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsGeneralTest.kt
Labels: 🛬 needs landing

#7301 For #7300: Upgrade Robolectric to 4.8.1
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#7304 Submit commits to Glean probe-scraper
  .github/workflows/glean-probe-scraper.yml
Labels: 🛬 needs landing

#7198 For #6167 Refactor FingerPrint to Biometric
  app/build.gradle
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/biometrics/BiometricAuthenticationDialogFragment.kt
  app/src/main/java/org/mozilla/focus/biometrics/BiometricAuthenticationFragment.kt
  app/src/main/java/org/mozilla/focus/biometrics/BiometricAuthenticationFragmentCompose.kt
  app/src/main/java/org/mozilla/focus/biometrics/BiometricAuthenticationHandler.kt
  app/src/main/java/org/mozilla/focus/biometrics/Biometrics.kt
  app/src/main/java/org/mozilla/focus/biometrics/LockObserver.kt
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
  app/src/main/java/org/mozilla/focus/settings/privacy/PrivacySecuritySettingsFragment.kt
  app/src/main/java/org/mozilla/focus/topsites/TopSitesIntegration.kt
  app/src/main/res/drawable/ic_fingerprint.xml
  app/src/main/res/layout/biometric_prompt_dialog_content.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/focus/biometrics/BiometricAuthenticationFragmentTest.kt
Labels: 🛬 needs landing

#7306 Record tracking protection cfr exposure only once
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/cfr/CfrMiddleware.kt
Labels: 🛬 needs landing
