Repository mozilla-mobile/focus-android, pull requests merged in 2022-02, with the labels that each got.

#6295 Add secret screen
  app/src/main/java/org/mozilla/focus/experiments/NimbusSetup.kt
  app/src/main/java/org/mozilla/focus/fragment/about/AboutFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/about/SecretSettingsUnlocker.kt
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
  app/src/main/java/org/mozilla/focus/settings/advanced/AdvancedSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/settings/advanced/SecretSettingsFragment.kt
  app/src/main/java/org/mozilla/focus/state/AppAction.kt
  app/src/main/java/org/mozilla/focus/state/AppReducer.kt
  app/src/main/java/org/mozilla/focus/state/AppState.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/advanced_settings.xml
  app/src/main/res/xml/secret_settings.xml
Labels: 🛬 needs landing

#5948 Remove current app from share list
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/utils/IntentUtils.kt
Labels: 🛬 needs landing

#6304 Avoid setting a second SessionFeature for a custom tab.
  app/src/main/java/org/mozilla/focus/activity/CustomTabActivity.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#6338 For #6331 - Focus crashes when accessing the "Add a search engine" SU…
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/utils/CfrUtils.kt
Labels: 🛬 needs landing

#6344 For #6332 - Properly anchor the Tracking Protection CFR
  app/src/androidTest/java/org/mozilla/focus/helpers/FeatureSettingsHelper.kt
  app/src/androidTest/java/org/mozilla/focus/privacy/LocalSessionStorageTest.kt
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/utils/CfrUtils.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/test/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegrationTest.kt
Labels: 🛬 needs landing

#6343 Move Secret Settings strings to static_strings.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#6354 mergify: delete relbot PR branch after merge
  .mergify.yml
Labels: 🛬 needs landing

#6366 For #6297 - Add flag for CFR Shield Icon to be shown only in DevOrNig…
  app/src/main/java/org/mozilla/focus/utils/CfrUtils.kt
  app/src/main/java/org/mozilla/focus/utils/Features.kt
Labels: 🛬 needs landing

#6375 Set version to 98.0
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#6377 Bump version to 99.0.0-beta.1
  version.txt
Labels: 🛬 needs landing

#6382 Set versionName to 99.0
  app/build.gradle
Labels: 🛬 needs landing

#6351 For #6211 - Tool Tip for: Privacy and Security Settings page
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/settings/privacy/PreferenceToolTipCompose.kt
  app/src/main/java/org/mozilla/focus/settings/privacy/PrivacySecuritySettingsFragment.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusColors.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusTheme.kt
  app/src/main/java/org/mozilla/focus/utils/Features.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/layout/focus_preference_compose_layout.xml
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/privacy_security_settings.xml
Labels: UX, 🛬 needs landing

#6391 No issue: Bump AC and fix breaking changes with providerConfig for top sites
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt
  app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt
  app/src/main/java/org/mozilla/focus/topsites/DefaultTopSitesStorage.kt
  app/src/test/java/org/mozilla/focus/topsites/DefaultTopSitesStorageTest.kt
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#6395 For #6393: Ensure that browser fragment is initialised and added to activity.
  app/src/main/java/org/mozilla/focus/activity/CustomTabActivity.kt
Labels: 🛬 needs landing

#6405 Enable HTTPS-only mode in Beta and Production release
  app/src/main/java/org/mozilla/focus/settings/HttpsOnlyModePreference.kt
  app/src/main/java/org/mozilla/focus/utils/Features.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
Labels: 🛬 needs landing

#6412 For #5841: Set explicit app package and class names for share intent.
  app/src/main/java/org/mozilla/focus/open/AppAdapter.java
  app/src/main/java/org/mozilla/focus/open/OpenWithFragment.java
Labels: 🛬 needs landing

#6348 For #6347 - Upgrade Espresso libraries for API 30
  app/build.gradle
  app/src/androidTest/java/org/mozilla/focus/activity/AddToHomescreenTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/EnhancedTrackingProtectionSettingsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/EraseBrowsingDataTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SearchTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ShareWebsiteTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ThreeDotMainMenuTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/CustomTabRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/DownloadRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/NotificationRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SearchRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsGeneralMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsMozillaMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SiteSecurityInfoSheetRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/ThreeDotMainMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityTestRule.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/RetryTestRule.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/focus/idlingResources/SessionLoadedIdlingResource.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/FirstRunScreenshots.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/HomeScreenScreenshots.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/SettingsScreenshots.kt
  automation/taskcluster/androidTest/flank-x86-beta.yml
  automation/taskcluster/androidTest/flank-x86-start-test.yml
  automation/taskcluster/androidTest/flank-x86.yml
  build.gradle
Labels: eng:ui-test, 🛬 needs landing (squash)

#6435 Update to Android-Components 99.0.20220214232836
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#6422 For #6416: Manually handle orientation changes in the custom tab activity
  app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#6452 Disable testCustomTabUI UI test
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
Labels: eng:ui-test, 🛬 needs landing

#6444 Close #6443: Apply experiments after fetching during startup
  app/src/main/java/org/mozilla/focus/experiments/NimbusSetup.kt
Labels: 🛬 needs landing

#6449 Add comments to strings.xml Tool Tip for Privacy and Security Screen
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#6463 No issue: Reduce number of FTL shards by pairing tests
  automation/taskcluster/androidTest/flank-x86.yml
  taskcluster/ci/ui-test/kind.yml
Labels: 🛬 needs landing

#6461 for #5310 Integrate LeakCanary
  app/build.gradle
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
  app/src/debug/AndroidManifest.xml
  app/src/debug/java/org/mozilla/focus/DebugFocusApplication.kt
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/settings/advanced/AdvancedSettingsFragment.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/static_strings.xml
  app/src/main/res/xml/advanced_settings.xml
  buildSrc/src/main/java/Dependencies.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#6467 For #5597 - Support RTL in Settings -> Choose search engine
  app/src/main/java/org/mozilla/focus/search/SearchEngineListPreference.kt
  app/src/main/res/layout/preference_screen_header_layout.xml
  app/src/main/res/layout/search_engine_radio_button.xml
Labels: 🛬 needs landing

#6489 For #6487 - Update compose to 1.1.0 and kotlin to 1.6.10
  app/src/main/java/org/mozilla/focus/browser/BlockedTrackersMiddleware.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchOverlay.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryMiddleware.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#6490 for #4958 Replace deprecated Fragment.onActivityCreated()
  app/src/main/java/org/mozilla/focus/fragment/AddToHomescreenDialogFragment.kt
Labels: 🛬 needs landing

#6451 Override versionName for shipping builds
  app/build.gradle
  buildSrc/src/main/java/Config.kt
Labels: 🛬 needs landing

#6508 Update kotlin-coroutines to 1.6.0
  app/src/test/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegrationTest.kt
  app/src/test/java/org/mozilla/focus/topsites/DefaultTopSitesStorageTest.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#6510 For #6503 When Renaming a Shortcut the Favicon / Letter Should Reflec…
  app/src/main/java/org/mozilla/focus/topsites/TopSites.kt
Labels: 🛬 needs landing

#6450 Integrate Picture-in-Picture feature
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#6527 Set nimbus preview default value to false
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
Labels: 🛬 needs landing
