Repository mozilla-mobile/focus-android, pull requests merged in 2022-10, with the labels that each got.

#7792 For #7580 re-enable Open custom tab in focus UI test
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/HomeScreenRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#7796 Remove extraneous coroutines_version
  build.gradle
Labels: 🛬 needs landing

#7803 Update some Gradle dependencies
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#7807 Update Kotlin to 1.7.20
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#7814 For #7689 - Don't open a new tab for a homeScreen shortcut when the theme is changed
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
Labels: 🛬 needs landing

#7822 No issue: remove old onboarding UI tests from FirstRunTest class
  app/src/androidTest/java/org/mozilla/focus/activity/FirstRunTest.kt
Labels: eng:ui-test, 🛬 needs landing

#7769 For #7678 - Redone all the navigation from lockscreen,search widget and custom tab
  app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
  app/src/main/java/org/mozilla/focus/biometrics/BiometricAuthenticationFragment.kt
  app/src/main/java/org/mozilla/focus/biometrics/LockObserver.kt
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
  app/src/main/java/org/mozilla/focus/navigation/Navigator.kt
  app/src/main/java/org/mozilla/focus/perf/Performance.kt
  app/src/main/java/org/mozilla/focus/searchwidget/ExternalIntentNavigation.kt
  app/src/main/java/org/mozilla/focus/state/AppAction.kt
  app/src/main/java/org/mozilla/focus/state/AppReducer.kt
  app/src/main/java/org/mozilla/focus/state/AppState.kt
  app/src/test/java/org/mozilla/focus/biometrics/BiometricAuthenticationFragmentTest.kt
  app/src/test/java/org/mozilla/focus/searchwidget/ExternalIntentNavigationTest.kt
Labels: 🛬 needs landing

#7844 For #7837 - "Browsing history cleared" should appear when promote search widget dialog is not shown
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
Labels: 🛬 needs landing

#7836 For #7838 re-enable UI tests with frequent ANR
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/EnhancedTrackingProtectionSettingsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ErrorPagesTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/WebControlsTest.kt
Labels: eng:ui-test, 🛬 needs landing

#7846 Update OkHttp MockWebServer dependency
  app/build.gradle
Labels: 🛬 needs landing

#7851 For #7838 re-enable notificationEraseAndOpenButtonTest UI test
  app/src/androidTest/java/org/mozilla/focus/activity/EraseBrowsingDataTest.kt
Labels: eng:ui-test, 🛬 needs landing

#7852 For #6792 - The colors of the icons from the toolbar should be in contrast with the toolbar background color
  app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#7813 For #5670: Align custom tab context menu list to Fenix.
  app/src/main/java/org/mozilla/focus/contextmenu/ContextMenuCandidates.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/test/java/org/mozilla/focus/contextmenu/ContextMenuCandidatesTest.kt
Labels: 🛬 needs landing

#7858 Pin relbot Github Action to the 1.0.0 tag
  .github/workflows/update-ac.yml
Labels: 🛬 needs landing

#7867 Update version.txt to 108.0b1.
  version.txt
Labels: 🛬 needs landing

#7876 Clean up and reorganize Gradle dependencies
  app/build.gradle
  build.gradle
  buildSrc/src/main/java/Dependencies.kt
  service-telemetry/build.gradle
Labels: 🛬 needs landing

#7883 Revert espresso-contrib back to 3.1.0-alpha4
  app/build.gradle
Labels: 🛬 needs landing

#7880 No issue: Attach client details (commit/PR) to test matrix
  automation/taskcluster/androidTest/ui-test.sh
Labels: 🛬 needs landing

#7906 Close #7905: Renew telemetry expiring <= 109
  app/metrics.yaml
Labels: 🛬 needs landing

#7918 For #7917: Upgrade AndroidX Annotation to 1.5.0.
  app/src/main/java/org/mozilla/focus/telemetry/ProfilerMarkerFactProcessor.kt
  app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/StartupActivityLog.kt
  app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/StartupPathProvider.kt
  app/src/main/java/org/mozilla/focus/telemetry/startuptelemetry/StartupTypeTelemetry.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#7911 Update Sentry to 6.6.0
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#7705 For #7503 - Show Start browsing cfr at fresh install
  app/build.gradle
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/FeatureSettingsHelper.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/MainActivityTestRule.kt
  app/src/androidTest/java/org/mozilla/focus/screenshots/ScreenshotTest.java
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/compose/CFRPopup.kt
  app/src/main/java/org/mozilla/focus/compose/CFRPopupShape.kt
  app/src/main/java/org/mozilla/focus/compose/Modifier.kt
  app/src/main/java/org/mozilla/focus/input/InputToolbarIntegration.kt
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
  app/src/main/java/org/mozilla/focus/state/AppAction.kt
  app/src/main/java/org/mozilla/focus/state/AppReducer.kt
  app/src/main/java/org/mozilla/focus/state/AppState.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusTypography.kt
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
  app/src/main/res/values/preference_keys.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/mozilla/focus/browser/integration/InputToolbarIntegrationTest.kt
  app/src/test/java/org/mozilla/focus/compose/CFRPopupTest.kt
Labels: 🛬 needs landing

#7889 For #6478 - Change "Search privately" string in "Search in 'app_name'"
  app/src/focusBeta/res/values/app.xml
  app/src/focusNightly/res/values/app.xml
  app/src/klar/res/values/app.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#7912 For #7874: Add AD_ID Permission
  app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#7933 No issue: Update Google Cloud SDK to 407.0.0
  taskcluster/docker/ui-tests/Dockerfile
Labels: 🛬 needs landing

#7947 For #7946: Remove deprecated methods from CustomTabsIntent.Builder
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: 🛬 needs landing
