Repository mozilla-mobile/focus-android, pull requests merged in 2022-03, with the labels that each got.

#6419 Delete android-accept-licenses.sh
  tools/docker/Dockerfile
  tools/docker/tools/android-accept-licenses.sh
Labels: 🛬 needs landing

#6533 Revert "For #6487 - Update compose to 1.1.0 and kotlin to 1.6.10"
  app/src/main/java/org/mozilla/focus/browser/BlockedTrackersMiddleware.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchOverlay.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryMiddleware.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#6530 For #6526 - Dismiss CFR when anchor disappears
  app/src/main/java/org/mozilla/focus/compose/CFRPopup.kt
Labels: 🛬 needs landing

#6532 [UI smoke test] For #6531: ads UI test for close tab button
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/TabsTrayRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#6537 For #6531 copy link address context menu UI smoke test
  app/src/androidTest/java/org/mozilla/focus/activity/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SearchRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#6555 Open Your Rights page in the existing tab
  app/src/main/java/org/mozilla/focus/tabs/MergeTabsMiddleware.kt
Labels: 🛬 needs landing

#6551 String updates on the new onboarding
  app/src/klar/res/values/app.xml
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingFragment.kt
  app/src/main/res/values/app.xml
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#6564 For #6531 web controls UI smoke tests
  app/src/androidTest/assets/htmlControls.html
  app/src/androidTest/java/org/mozilla/focus/activity/WebControlsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/ThreeDotMainMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#6562 [UI smoke test] For #6531: Ads new UI tests for main menu
  app/src/androidTest/java/org/mozilla/focus/activity/ShareWebsiteTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ThreeDotMainMenuTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/ThreeDotMainMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#6590 Remove ShareWebsiteTest UI test class
  app/src/androidTest/java/org/mozilla/focus/activity/ShareWebsiteTest.kt
Labels: eng:ui-test, 🛬 needs landing

#6592 For #6561: The new onboarding has discrepancies on dark mode
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingFragment.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusColors.kt
Labels: 🛬 needs landing

#6586 For #6585 Status bar for onboarding screen should have the same color…
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingFragment.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#6591 For #6531 date picker web control UI smoke test
  app/src/androidTest/assets/htmlControls.html
  app/src/androidTest/java/org/mozilla/focus/activity/WebControlsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#6572 For #6522 Focus Nightly crashes when accessing Your Rights page
  app/src/main/java/org/mozilla/focus/settings/MozillaSettingsFragment.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#6613 Set versionName 100
  app/build.gradle
Labels: 🛬 needs landing

#6599 Tab is not overridden in about:debugging
  app/src/main/java/org/mozilla/focus/tabs/MergeTabsMiddleware.kt
Labels: 🛬 needs landing

#6605 Remove unnecessary permission
  app/src/main/AndroidManifest.xml
Labels: 🛬 needs landing

#6557 No issue: Use version instead of date for telemetry/metrics expiration
  app/build.gradle
  app/metrics.yaml
Labels: 🛬 needs landing

#6598 For #6531 Cookies and Site Data menu items UI smoke test
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsPrivacyMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#6563 [UI smoke test] For #6531: Adds new UI test for themes
  app/src/androidTest/java/org/mozilla/focus/activity/SetDefaultBrowserTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsGeneralTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsGeneralMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#6643 [UI smoke test] For #6531: Ads new media notification UI test
  app/src/androidTest/java/org/mozilla/focus/activity/MediaPlaybackTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/NotificationRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#6659 For #6531 test cookies blocked UI smoke tests
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsPrivacyMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#6671 Disable systemBarHomeViewTest UI test
  app/src/androidTest/java/org/mozilla/focus/activity/EraseBrowsingDataTest.kt
Labels: eng:ui-test, 🛬 needs landing

#6663 For #6036 - Use app defined string for the cancel button
  app/src/main/res/xml/privacy_security_settings.xml
Labels: 🛬 needs landing

#6676 For #6531 improve testVisitingMultipleSites UI smoke test coverage
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/CustomTabRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/TabsTrayRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#6681 Do not notify the crash reporter of common Nimbus exceptions
  app/src/main/java/org/mozilla/focus/experiments/NimbusSetup.kt
  app/src/test/java/org/mozilla/focus/experiments/NimbusSetupTest.kt
Labels: 🛬 needs landing

#6689 Displays the onboarding screen in correct order for both RTL and LTR
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingFragment.kt
Labels: 🛬 needs landing

#6706 Disable failing MultitaskingTests UI tests
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
Labels: eng:ui-test, 🛬 needs landing

#6700 Bootstrap Taskgraph from pypi in decision task
  .taskcluster.yml
  taskcluster/focus_android_taskgraph/parameters.py
  taskcluster/requirements.in
  taskcluster/requirements.txt
Labels: eng:automation, 🛬 needs landing

#6696 For #6531 improve Verify Linking UI smoke tests coverage
  app/src/androidTest/java/org/mozilla/focus/activity/WebControlsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/Constants.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#6716 Add condition for verifying send data switch state in UI tests based on build variant
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsPrivacyMenuRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#6713 For #6709 and #6708 re-enable MultitaskingTests UI tests
  app/src/androidTest/assets/tab1.html
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
Labels: eng:ui-test, 🛬 needs landing

#6719 Revert "Bug 1760570 - disable nightlies until google play catches up"
  .cron.yml
Labels: 🛬 needs landing

#6728 For #6709 Disable failing testVisitingMultipleSites
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
Labels: eng:ui-test, 🛬 needs landing

#6730 No issue: Move native apps package names from Constants object to StringHelper object
  app/src/androidTest/java/org/mozilla/focus/activity/WebControlsTest.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/Constants.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/StringsHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#6767 Ignore autofill for add to home screen field
  app/src/main/res/layout/dialog_add_to_homescreen2.xml
Labels: 🛬 needs landing

#6763 Disable experiments by default on Klar variants
  app/src/main/java/org/mozilla/focus/utils/Settings.kt
Labels: 🛬 needs landing

#6765 Dismiss tabs popup when onStop is called
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing

#6746 For #6531 new verifyTabsTrayListTest UI Smoke test and other refactoring work
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/TabsTrayRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#6776 Update crash reporting intent flag
  app/src/main/java/org/mozilla/focus/Components.kt
Labels: 🛬 needs landing

#6750 Implementation of AndroidAssetsDispatcher helper in all test classes
  app/src/androidTest/assets/etpPages/adsTrackers.html
  app/src/androidTest/assets/etpPages/analyticsTrackers.html
  app/src/androidTest/assets/etpPages/otherTrackers.html
  app/src/androidTest/assets/etpPages/socialTrackers.html
  app/src/androidTest/assets/permissionsPage.html
  app/src/androidTest/java/org/mozilla/focus/activity/AddToHomescreenTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ContextMenusTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/CustomTabTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/EnhancedTrackingProtectionSettingsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/EraseBrowsingDataTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/FirstRunTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MediaPlaybackTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MozillaSupportPagesTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MultitaskingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/OpenInExternalBrowserDialogueTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SafeBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsAdvancedTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SettingsPrivacyTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ShortcutsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SwitchContextTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/ThreeDotMainMenuTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/WebControlsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsPrivacyMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsSearchMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestAssetHelper.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
  app/src/androidTest/java/org/mozilla/focus/privacy/LocalSessionStorageTest.kt
Labels: eng:ui-test, 🛬 needs landing

#6786 For #6783: Fix tab titles in verifyTabsTrayListTest
  app/src/androidTest/assets/tab1.html
  app/src/androidTest/assets/tab2.html
  app/src/androidTest/assets/tab3.html
  app/src/androidTest/java/org/mozilla/focus/activity/robots/TabsTrayRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestAssetHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#6788 Implement dark theme for the new onboarding screen
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingFragment.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusColors.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusTheme.kt
  app/src/main/java/org/mozilla/focus/ui/theme/FocusTypography.kt
Labels: 🛬 needs landing

#6800 Dismiss ETP when onStop is called
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
Labels: 🛬 needs landing
