Repository mozilla-mobile/focus-android, pull requests merged in 2022-05, with the labels that each got.

#6948 For #6487 - Update compose to 1.1.1 and kotlin to 1.6.10
  app/src/main/java/org/mozilla/focus/browser/BlockedTrackersMiddleware.kt
  app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchOverlay.kt
  app/src/main/java/org/mozilla/focus/telemetry/TelemetryMiddleware.kt
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#6913 Swap the order of two tips to make more sense
  app/src/androidTest/java/org/mozilla/focus/activity/FirstRunTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/MozillaSupportPagesTest.kt
  app/src/main/java/org/mozilla/focus/tips/TipManager.kt
Labels: 🛬 needs landing

#6956 Set version to 101.0
  buildSrc/src/main/java/AndroidComponents.kt
Labels: 🛬 needs landing

#6910 No issue: Add telemetry data renewal helper script
  tools/data_renewal_generate.py
Labels: 🛬 needs landing

#6949 Update kotlin-coroutines to 1.6.0 for testing
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#6950 Update the fill color of klar logo
  app/src/klar/res/drawable/wordmark2.xml
Labels: 🛬 needs landing

#6980 Add context for nimbus feature value
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/cfr/CfrMiddleware.kt
  app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
  app/src/main/java/org/mozilla/focus/tabs/MergeTabsMiddleware.kt
  app/src/test/java/org/mozilla/focus/cfr/CfrMiddlewareTest.kt
Labels: 🛬 needs landing

#6999 for #6979 fixed focus crash when the fingerprint auth is deleted
  app/src/main/java/org/mozilla/focus/biometrics/BiometricAuthenticationDialogFragment.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#6996 for #6792 [custom tab] Fixed Toolbar icons color.
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
Labels: 🛬 needs landing

#7005 Align onboarding title to center
  app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingFragment.kt
Labels: 🛬 needs landing

#6994 Record multi tabs experiment on context menu
  app/src/main/java/org/mozilla/focus/contextmenu/ContextMenuCandidates.kt
Labels: 🛬 needs landing

#6972 Record telemetry for nimbus experiments fetching
  app/metrics.yaml
  app/src/main/java/org/mozilla/focus/experiments/NimbusSetup.kt
Labels: 🛬 needs landing

#7010 Set tracking cfr to false on dismiss
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
Labels: 🛬 needs landing

#7029 for #6890 Create unit tests for SitePermissions.
  app/src/main/java/org/mozilla/focus/settings/permissions/SitePermissionsFragment.kt
  app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/SitePermissionOptionsStorage.kt
  app/src/test/java/org/mozilla/focus/sitepermissions/SitePermissionOptionsStorageTest.kt
  app/src/test/java/org/mozilla/focus/sitepermissions/SitePermissionOptionsStoreTest.kt
  app/src/test/java/org/mozilla/focus/sitepermissions/SitePermissionsFragmentTest.kt
Labels: 🛬 needs landing

#7030 Splash screen updates
  app/src/beta/res/drawable-v24/ic_splash_screen.xml
Labels: 🛬 needs landing

#7036 Record nimbus exposure only at feature interaction
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
Labels: 🛬 needs landing

#7045 Record nimbus exposure only at feature interaction
  app/src/main/java/org/mozilla/focus/cfr/CfrMiddleware.kt
  app/src/main/java/org/mozilla/focus/tabs/MergeTabsMiddleware.kt
Labels: 🛬 needs landing

#7084 for #6895 [PiP] Fingerprint auth prompt should not overlay on video in PiP mode
  app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#7086 Update tracking protection cfr visibility conditions
  app/src/main/java/org/mozilla/focus/cfr/CfrMiddleware.kt
  app/src/test/java/org/mozilla/focus/cfr/CfrMiddlewareTest.kt
Labels: 🛬 needs landing

#7094 Update splash screen beta logo
  app/src/beta/res/drawable-v24/ic_splash_screen.xml
Labels: 🛬 needs landing

#7101 No issue: add performance issue template.
  .github/ISSUE_TEMPLATE/---performance-issue.md
Labels: 🛬 needs landing

#7097 For #6958, #6967: fixed settings switch and radio buttons selectors, scrolling on Settings menus lists
  app/src/androidTest/java/org/mozilla/focus/activity/SafeBrowsingTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/SitePermissionsTest.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsPrivacyMenuRobot.kt
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsSitePermissionsRobot.kt
Labels: eng:ui-test, 🛬 needs landing

#7106 for #7057 Update the fingerprint settings summary
  app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsPrivacyMenuRobot.kt
  app/src/main/java/org/mozilla/focus/settings/privacy/PrivacySecuritySettingsFragment.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/privacy_security_settings.xml
Labels: 🛬 needs landing

#7111 Fix #7075: make toolbar visible on navigation or load request changes
  app/src/main/java/org/mozilla/focus/browser/integration/BrowserToolbarIntegration.kt
Labels: 🛬 needs landing

#7133 Remove redundant record exposure
  app/src/main/java/org/mozilla/focus/Components.kt
Labels: 🛬 needs landing

#7141 Update versionName to 103.0
  app/build.gradle
Labels: 🛬 needs landing
