Repository mozilla-mobile/focus-android, pull requests merged in 2022-07, with the labels that each got.

#7310 For #7309: Show storage access prompts when requested
  app/src/main/java/org/mozilla/focus/settings/permissions/permissionoptions/SitePermissionOptionsStorage.kt
Labels: 🛬 needs landing

#7319 for #7236 Add metrics tags for all issues labels
  app/metrics.yaml
  app/tags.yaml
Labels: 🛬 needs landing, needs:data-review

#7325 Remove unused strings marked moz:removedIn <= 101
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#7332 Apply cfr nimbus feature from the first run
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/cfr/CfrMiddleware.kt
  app/src/main/java/org/mozilla/focus/experiments/NimbusSetup.kt
Labels: 🛬 needs landing

#7351 For #7105, #7163 UI tests: Retry click on media player Play button
  app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/Constants.kt
Labels: eng:ui-test, 🛬 needs landing

#7349 For #5896 - Fix branches naming scheme for the sync-strings action
  .github/workflows/sync-strings.yml
Labels: 🛬 needs landing

#7357 For #6507, #6500 UI tests: randomize page shortcut title, fix URL confusions.
  app/src/androidTest/java/org/mozilla/focus/activity/AddToHomescreenTest.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#7369 Bug 1779797 - Let mergify automatically approve all l10n bumps
  .mergify.yml
Labels: 🛬 needs landing

#7375 For #7374: Replace deprecated androidx_lifecycle-extensions with lifecycle-process.
  app/build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#7377 Issue #7376 - use mock location in UI tests
  app/src/androidTest/java/org/mozilla/focus/activity/SitePermissionsTest.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/MockLocationUpdatesRule.kt
  app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Labels: eng:ui-test, 🛬 needs landing

#7386 For #7385: Cleanup and update dependencies
  app/build.gradle
  buildSrc/src/main/java/Dependencies.kt
Labels: 🛬 needs landing

#7393 Closes #7392: Upgrade Gradle to 7.3.3.
  buildSrc/build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: 🛬 needs landing

#7396 Bug 1777255 - part 3: Bump focus-android-beta-version Github Action t…
  .github/workflows/sync-strings.yml
Labels: 🛬 needs landing

#7405 For #1640: Map ISO 639-1 code to language name for Navajo.
  app/src/main/java/org/mozilla/focus/locale/screen/LocaleDescriptor.kt
Labels: 🛬 needs landing

#7409 Bug 1780740 - A-C bumps should auto-merge if CI is green on release branches
  .mergify.yml
Labels: 🛬 needs landing

#7404 For #6641 - Fix directionality for RTL in the about screen
  app/src/main/java/org/mozilla/focus/fragment/about/AboutFragment.kt
Labels: 🛬 needs landing

#7395 For #7388 - Add GitHub actions to tag milestones, link issues and reopen issues for QA
  .github/PULL_REQUEST_TEMPLATE
  .github/workflows/issue-linker.yml
  .github/workflows/milestone.yml
  .github/workflows/qa-needed.yml
  .github/workflows/reopen-for-qa-needed.yml
Labels: 🕵️‍♀️ needs review, 🛬 needs landing

#7414 Update version.txt to 105.0b1
  version.txt
Labels: 🛬 needs landing

#7417 Remove all unused strings marked moz:removedIn <= 102
  app/src/main/res/values/strings.xml
Labels: 🛬 needs landing

#7206 For #7180 Remove GeckoExceptionsMigrator in or before version 106
  app/src/main/java/org/mozilla/focus/Components.kt
  app/src/main/java/org/mozilla/focus/FocusApplication.kt
  app/src/main/java/org/mozilla/focus/components/EngineProvider.kt
  app/src/main/java/org/mozilla/focus/exceptions/GeckoExceptionsMigrator.kt
Labels: 🛬 needs landing
